### ISSUE TITLE
Agenda and Minutes 2021-12-17

### ISSUE THREAD

**Issue by alexulven** [hackforla/311-data#1161]
### Overview
This issue tracks the agenda for the PM/Org meetings for the 311-data project

### Resources
Add a link to each comment below (each one being an agenda and meeting minutes

### Past
[2021-12-17](https://github.com/hackforla/311-data/issues/1161#issuecomment-997103445)

**Comment by ExperimentsInHonesty** [comment]
## Agenda and Minutes 2021-12-17

### Prework
- [ ] label audit #1134

### Roll Call
Bonnie, Lexi, Eric

#### Recurring items: 
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/311-data/projects/10#column-15704782)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/311-data/issues/assigned/ExperimentsInHonesty)
       - [ ] [Eric](https://github.com/hackforla/311-data/issues/assigned/EchoProject)
       - [ ] [Alexandra](https://github.com/hackforla/311-data/issues/assigned/alexulven)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/311-data/issues?q=is%3Aopen+is%3Aissue+label%3AEpic) and define how to break down further

#### New Items
- [ ] #337
- [ ] Review User Stories 

#### Actions taken or notes about stuff from the meeting:
- Regan added this text to the top of this issue #337.  It didn't seem relevant so I removed it during the check on issues in the new issue approval column
> **UPDATE LABELS: Add the following labels to each new issue, and remove defaults:**
> * Role
> * Feature
> * Points 
> * Milestone
- Bonnie and Kristy rewrote the description for the hackforla.org website and revised the issue #337 from new issue approval and put it into the prioritized backlog

#### New Task Items
- [ ] Make an issue for the user stories or identify which issue its in, so that we can add it to the agenda
- [ ] Kristy will remove the calendar invites for 24th and 31st
- [ ] Next meeting add Surbi to the 1password

**Comment by ExperimentsInHonesty** [comment]
## Agenda and Minutes 2021-12-17

### Prework
- [ ] label audit #1134

### Roll Call
Bonnie, Eric

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/311-data/projects/10#column-15704782)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/311-data/issues/assigned/ExperimentsInHonesty)
       - [ ] [Eric](https://github.com/hackforla/311-data/issues/assigned/EchoProject)
       - [ ] [Alexandra](https://github.com/hackforla/311-data/issues/assigned/alexulven)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/311-data/issues?q=is%3Aopen+is%3Aissue+label%3AEpic) and define how to break down further

#### New Items
- [ ] Icebox review to see what is going on with the issues with no dependency
   - pushed to next meeting

#### Actions taken or notes about stuff from the meeting:

#### New Task Items
- [ ] scheduling next steps for driving the labels missing count down, if it has not changed.

- [ ] Lets see if Lexie to Follow up with Chelsey to see all the issues she is currently assigned to that affect the project and prioritize what we need to know. https://github.com/hackforla/311-data/issues/1137
    - [ ] Has she worked on this at all (including just writing documentation https://github.com/hackforla/311-data/issues/699) and can she estimate size
- [ ] Eric will review the icebox for the issues that don't have a dependency to see what we need to do next https://github.com/hackforla/311-data/projects/10?card_filter_query=-label%3Adependency 
- [ ] Did a roadmap issue get made
    - [Open Community Survey Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
   - [Guides Team Roadmap Example](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
   - Guides Team Milestones https://github.com/hackforla/guides/milestones
- [ ] Did Eric to combo these two issue together (this agenda issue and issue #1136)

**Comment by ExperimentsInHonesty** [comment]
## Agenda and Minutes 

### Prework
- [ ] label audit #1134

### Roll Call


#### Recurring items: 
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/311-data/projects/10#column-15704782)
 - [x] Accountability and Support Check
    - [x] Review assignments for each PM
       - [x] [Bonnie](https://github.com/hackforla/311-data/issues/assigned/ExperimentsInHonesty)
       - [x] [Eric](https://github.com/hackforla/311-data/issues/assigned/EchoProject)
       - [x] [Alexandra](https://github.com/hackforla/311-data/issues/assigned/alexulven)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/311-data/issues?q=is%3Aopen+is%3Aissue+label%3AEpic) and define how to break down further

#### New Items
- [x] Icebox review to see what is going on with the [issues with no dependency](https://github.com/hackforla/311-data/projects/10?card_filter_query=-label%3Adependency#column-11518033)

#### Actions taken or notes about stuff from the meeting:
- Lexie has not yet left any notes on her issue to follow up with Chelsey.  Bonnie asked for update.  Issue will be carried into next meeting
- Answered Erics questions about how to combo the agenda issues and meeting notes

#### New Task Items
- [ ] scheduling next steps for driving the labels missing count down, if it has not changed.
- [x] Lets see if Lexie to Follow up with Chelsey to see all the issues she is currently assigned to that affect the project and prioritize what we need to know. https://github.com/hackforla/311-data/issues/1137
    - [ ] Has she worked on this at all (including just writing documentation https://github.com/hackforla/311-data/issues/699) and can she estimate size
- [x] Eric will review the icebox for the issues that don't have a dependency to see what we need to do next https://github.com/hackforla/311-data/projects/10?card_filter_query=-label%3Adependency 
- [x] Did a roadmap issue get made - Yes it did https://github.com/hackforla/311-data/issues/1162
- [x] Did Eric to combo these two issue together (this agenda issue and issue #1136)

**Comment by ExperimentsInHonesty** [comment]
This issue has been closed because we have combined it with an older agenda issue which has all Erics notes from our PM meetings, which we did not want to lose track of.
