### ISSUE TITLE
Fix Incorrect Data on 311 Data Dashboard

### ISSUE THREAD

**Issue by akhaleghi** [hackforla/311-data#1230]
### Overview
The Neighborhood Weekly Report on the 311 Data Dashboard shows an incorrect city name.

### Action Items
- [ ] Visit https://dev.311-data.org/map and navigate (through the top menu) to Reports-> Neighborhood Weekly
- [ ] See that first line of text below the drop-down menu says 'Arleta weekly report (dates)' remains the same as you change to different cities in the drop-down menu.
- [ ] Fix this bug by having the city name in the line of text match the item selected in the drop-down menu.
   - See https://dev.311-data.org/map Reports -> Neighborhood for an example where the title of the charts reflect the city selected in the drop-down menu.

### Resources/Instructions
[311 Data Dashboard](https://dev.311-data.org/map)

![neighborhood_mismatch](https://user-images.githubusercontent.com/7635911/156270730-56cdf73b-3d45-4f08-b9fd-d3bf97c3d039.png)

**Comment by joshuayhwu** [comment]
This is an issue with the <NC name> below the drop down. being assigned as a global variable, while the filtering mechanism of the drop down utilize dash call backs that is separate from this variable.

 All the filtering functionality work on the dashboard (i.e. data is correct). To avoid adding additional complexity, I removed the duplicate <NC name> on the line below the drop down.

![IncorrectDataTicket](https://user-images.githubusercontent.com/77765986/172784532-a7bd3bd5-4c4c-44b2-8b85-a865b850f0d5.PNG)
