### ISSUE TITLE
Show source information on file exports

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/311-data#1231]
### Overview

Currently, when someone exports an image, csv, or PDF, the source information isn't there. We should be including a reference to our site, to the data source, and information regarding the query like the date it was generated, NC, request type, etc.

### Action Items
 
- [ ] PNG Export (contains all these items visible at the bottom
- [ ] CSV Export (contains info towards the top of the CSV
- [ ] PDF export (ideally in the footer)

Research whether or not we can add this functionality in Plotly Dash

### Resources/Instructions

[311-data project onboarding](https://docs.google.com/document/d/1fNIxKJl91YZ_b6PRvKMdyd7tXJwWbfGIAJ5VTfe8Jow/edit?pli=1#heading=h.c8tc614ce3iu)

Refer to the documentation in the [311-data dashboards directory](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards) for creating or modifying dashboards

[Dash Python User Guide](https://dash.plotly.com/)

Optional: prototype reports in Jupyter Notebooks -examples found [here](https://drive.google.com/drive/u/3/folders/1P-uID8FpnqwvYlUmzWsmgU4pxRSeb72z).
