### ISSUE TITLE
Add a high-level description for each 311-data app dashboard

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/311-data#1233]
### Overview
Add a high-level description to each report/dashboard on the 311-data app to add more context for viewers.

### Action Items

- [x] add high-level description to [overview dashboard](https://dev.311-data.org/reports/dashboards/overview)
- [x] add high-level description to [recent dashboard](https://dev.311-data.org/reports/dashboards/recent)
- [ ] add high-level description to [neighborhood dashboard](https://dev.311-data.org/reports/dashboards/neighborhood)
- [ ] add high-level description to neighborhood [recent dashboard](https://dev.311-data.org/reports/dashboards/neighborhood_recent)
- [ ] add high-level description to [request type map](https://dev.311-data.org/reports/dashboards/types_map)

### Resources/Instructions
[311-data project onboarding](https://docs.google.com/document/d/1fNIxKJl91YZ_b6PRvKMdyd7tXJwWbfGIAJ5VTfe8Jow/edit?pli=1#heading=h.c8tc614ce3iu)
Refer to the documentation in the [311-data dashboards directory](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards) for creating or modifying dashboards

[Dash Python User Guide](https://dash.plotly.com/)

- #1378

**Comment by joshuayhwu** [comment]
Combined dashboard and updated title names render this issue redundant.
