### ISSUE TITLE
Improve Key on 311 Data Dashboard Neighborhood Report

### ISSUE THREAD

**Issue by akhaleghi** [hackforla/311-data#1235]
### Overview
The Neighborhood Report on the 311 Data Dashboard needs a more descriptive key for the first chart.

### Action Items
- [x] Visit https://dev.311-data.org/map and navigate (through the top menu) to Reports-> Neighborhood
- [x] The key for the first chart (circled in the attached image) needs a few bug fixes. 
   - [x] 'count' should be 'Counts' to match the text in the keys that follow.
   - [x] 'nc_avg' needs a more descriptive title. 
      - [x] Research what nc_avg represents by reviewing the source code and data. It is NOT an average of counts for all neighborhood councils on that date, as when you change between councils with the drop down menu the values change for the purple line.
      - [x] Once it has been determined what this line represents, change the name in the key accordingly.

### Resources/Instructions
[311 Data Dashboard](https://dev.311-data.org/map)

![neighborhood_key](https://user-images.githubusercontent.com/7635911/156269750-10225c22-0923-4dd8-84a8-e6645cc3f005.png)

- #1378

**Comment by piotrsan** [comment]
Created pull request with the updates to neighborhood.py dashboard:

https://github.com/hackforla/311-data/pull/1242

**Comment by joshuayhwu** [comment]
> Hi @akhaleghi,
> 
> yes I was able to generate the different averages and change the labels to the graph. I need to know create the dropdown.
> 
> I still need a bit of help in understanding how to push changes I made for revision. Currently I cloned the 311-data repo to my GitHub. Should I generate a pull request of the file that I have been working on?
> 
> I was only able to visualize two months worth of data, is there any way to visualize more data using the docker implementation described in the dashboard folder?
> 
> Thanks,

@piotrsan If you follow the [docker setup documentation](https://github.com/hackforla/311-data/blob/dev/docs/server_setup.md), you should be able to get the 4 containers running in docker with multiple years of data (defined in step 3). From there, follow the [dashboard documentations](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards) and you should be able run the dashboard with more data.

**Comment by nichhk** [comment]
It looks like the API intentionally limits the data returned to cover the current month and the previous month only: https://github.com/hackforla/311-data/blob/dev/server/api/code/lacity_data_api/routers/reports.py#L28. It looks like this was added to speed things up, see issue #986 and PR #989.

Let's discuss tonight whether we want to make the /reports API take a parameter for # of months.

**Comment by joshuayhwu** [comment]
Combined dashboard render this redundant.
