### ISSUE TITLE
Mobile Menu Redesign

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1300]
### Overview
We need to redesign the mobile menu to streamline the mobile experience while preserving all features of the desktop version.

### Action Items
- [x] Redesign map to fit a mobile screen
- [x] Experiment with menu prompts in order to find one that functions well without interrupting user flow
- [x] Relocate the information tooltip to the FAQ page [reference issue #1297](https://github.com/hackforla/311-data/issues/1297)
- [x] #1319 Add tool tips for mobile menu.

### Resources/Instructions
Past Menu Design
![image](https://user-images.githubusercontent.com/97048386/181650798-4d4694fd-1325-47de-81e1-4cbf75af2d4a.png)

- [ ] Make council searching more user-friendly on Map [reference issue #1306](https://github.com/hackforla/311-data/issues/1306)

**Comment by melissahermes99** [comment]
I've created three different versions of possible menus. However, after discussion during a team meeting, we will be going with the clickable pop-up in order to save screen real estate.

-  **Horizontal Scroll**
![image](https://user-images.githubusercontent.com/97048386/181652327-231fd89a-f304-4caa-88e8-c29c698534eb.png)  

- **Vertical Scroll**
 ![image](https://user-images.githubusercontent.com/97048386/181652392-a20d8346-2eab-411b-b398-b088313a09b5.png)

- **Clickable Pop-up**
 ![image](https://user-images.githubusercontent.com/97048386/181652640-27858a1d-7f2e-4bd6-bf02-da0b26c286ed.png)

**Comment by melissahermes99** [comment]
I've created a four-step tutorial for the mobile menu which includes the following :
- Start by entering an address
- Tap here to adjust filters and settings
- To adjust distance and location, swipe, pinch, or tap your screen
- Tap points to see details

[Click here to view prototype](https://www.figma.com/proto/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5024%3A14165&scaling=scale-down&page-id=3266%3A10&starting-point-node-id=5024%3A14165&show-proto-sidebar=1)

![image](https://user-images.githubusercontent.com/97048386/181658574-6e2f5e0a-0b1d-4581-803d-5f42b40895f3.png)

**Comment by EchoProject** [comment]
@melissahermes99 and @edwinjue this issue for mobile design will need to be addressed in a future iteration beyond the initial v2 launch. Let's reconnect on this after the holidays.

**Comment by EchoProject** [comment]
Closing this issue as it has been passed onto engineering.

**Comment by EchoProject** [comment]
My mistake, closed by accident.

**Comment by mc759** [comment]
Hey @melissahermes99 Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
