### ISSUE TITLE
Thematic Coloring of Content Pages

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1347]
### Overview
We need to change the background colors of content pages (Reports, FAQ, About, Blog Privacy, Contact) to white to create a default white mode for the website.

### Action Items
- [x] Finalize[ theme.js](https://github.com/hackforla/311-data/blob/dev/client/theme/theme.js) to support light theme (this includes changing the background colors of content pages to #FFFFFF White among other palette specifications). This [tool](https://bareynol.github.io/mui-theme-creator) may help. (`proposed changes`: [light theme v1](https://gist.github.com/edwinjue/cd45c480c749c8d1e5062c1378a2daf7))
- [x] Across all pages, identify all custom styles (i.e. - makeStyles) that may have an impact on the application of light theme and address each individually
- [x] Eventually, will need to finalize [typography.js](https://github.com/hackforla/311-data/blob/dev/client/theme/typography.js) and apply thematic typography across all pages to inherit font family/style/weight from theme.js (`proposed changes`: [light theme v1 - typography](https://gist.github.com/edwinjue/ccec0fe0bd38540c0c2f477ee1d7d145)) (may need to separate this into a separate issue)
- [x] Eventually, will need to ensure consistent spacing is applied among page items on every page such as spacing between the page heading and content so navigating from page to page does not cause any unwanted movement ([example](https://stackoverflow.com/questions/8975174/website-layout-moving-slightly-between-pages-how-to-stop-it)).  (may need to separate this into a separate issue)

### Screenshots 
_(Progress made as of 9/30/22)_
### Map
Will be updating this in [#1370](https://github.com/hackforla/311-data/issues/1370)

### FAQ
![image](https://user-images.githubusercontent.com/1448719/193231525-ec5bf60e-d152-446f-aff5-a2dfd53455f1.png)
**FAQ Open Items:**
- [ ] #1384
- [ ] #1385

### About
![image](https://user-images.githubusercontent.com/1448719/193231593-232dc189-2c09-4f08-9d39-32e4aa4f8204.png)
**About Open Items:**
- [x] About - All Completed

### Privacy Policy
![image](https://user-images.githubusercontent.com/1448719/193231663-67e4386f-c7e1-46c0-ac4d-d9e3cd3c48ea.png)
**Privacy Policy Open Items:**
- [ ] #1383

### Contact
![image](https://user-images.githubusercontent.com/1448719/193231735-865a4a9f-2c47-4281-aa43-d475a9d05002.png)
**Contact Open Items:**
- [x] Contact - All Completed

### Related Pull-Requests
[#1 v2 dependencies #1386](https://github.com/hackforla/311-data/pull/1386/files) _(merged on 10/3/22)_
[#2 v2 new components #1388](https://github.com/hackforla/311-data/pull/1388) _(merged on 10/4/22)_
[#3 v2 header & footer updates #1389](https://github.com/hackforla/311-data/pull/1389) _(merged on 10/5/22)_
[#4 v2 About page](https://github.com/hackforla/311-data/pull/1390) _(merged on 10/6/22)_
[#5 v2 FAQs](https://github.com/hackforla/311-data/pull/1391)  _(merged on 10/5/22)_
[#6 v2 Privacy ](https://github.com/hackforla/311-data/pull/1392) _(merged on 10/5/22)_
[#7 v2 Contact](https://github.com/hackforla/311-data/pull/1393) _(merged on 10/6/22)_
[#8 v2 map initial](https://github.com/hackforla/311-data/pull/1394) _(merged on 10/6/22)_

### Useful Tools

- [ ] [Web Font Helper](https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=latin): To explore how different Google Web fonts appear on the web
- [ ] [Material-UI Theme Creator](https://bareynol.github.io/mui-theme-creator/): To visualize how different Material-UI theme settings look in real-time

**Comment by nichhk** [comment]
@melissahermes99 , do you have a suggestion for the color of text against a white background? We have some colors [here](https://github.com/hackforla/311-data/blob/dev/client/theme/theme.js#L33), but not sure if we want to use any of these.

**Comment by melissahermes99** [comment]
Let's try #29404F for the text and if that appears too light against the background we can switch it to #0F181F. I do have some frames on Figma that are using #29404F for the text already so it should be a good option!

**Comment by edwinjue** [comment]
@melissahermes99 hope all's well. Just wanted to get your feedback on the latest update per the updated screenshots in the first screenshot. @nichhk and I would like your feedback on whether they resemble the V2 figma designs enough to move these changes into the dev branch. Please let us know. If there are any changes you'd like us to make, please let us know too. Looking forward to your feedback! Thanks!

**Comment by melissahermes99** [comment]
@edwinjue The progress is looking great! I'm not sure if it's just how the colors are presented on my screen but the primary color on the header space should be #29404F. We also did away with the secondary titles on each page aside from the FAQ page where the header space is filled with a search bar; So on the Privacy Policy page we can remove the secondary "Privacy Policy title". Other than that, I think everything is looking perfect! Elizabeth and I have adjusted the margins, fonts, colors, and text sizes to hopefully make things easier for you!

**Comment by edwinjue** [comment]
@melissahermes99 thanks for the feedback! 

I've updated the screenshots to reflect the new header space color #29404F (check first post). 

Regarding your other concerns, I went ahead and logged each as a new issue so we can address them as soon as the pull requests successfully merge with dev:

- [ ] [Need to update contentful.com to mirror the content in figma (e.g. - remove the Privacy Policy heading from the content area) #1383](https://github.com/hackforla/311-data/issues/1383)
- [ ] [Need to add the search feature to header of FAQs page (refer to v2 figma design - FAQs) #1384](https://github.com/hackforla/311-data/issues/1384)
- [ ] [Need to create expandable/collapsible section headings for FAQs page per v2 figma design #1385](https://github.com/hackforla/311-data/issues/1385)

I should warn you these changes will present some color related issues to the desktop menu on the Map page. However, a plan is already in place to address this as soon as this version goes live on dev #1370 

Please let me know if what I presented satisfies your concerns sufficiently and whether we have the go ahead from you to make the changes live on our dev site

Thanks!

**Comment by melissahermes99** [comment]
Everything checks out with me, it's looking great! Thanks for going ahead and creating the new issues, I really appreciate it!

**Comment by edwinjue** [comment]
hi @melissahermes99

Thanks to the help of @nichhk, @jekijo and @funbunch the folks at engineering were able to update the content pages to the v2 design in a timely fashion. When you have time, feel free to take a look and let us know what you think. 

@melissahermes99 I may have mentioned that pull request #1394 would have addressed your [comment](https://github.com/hackforla/311Idata/pull/1342#issuecomment-1261534533) on #1342 but this will happen during one of the first commits when we work on #1370. Just thought I'd let you know. Hope you've been well

**Comment by melissahermes99** [comment]
@edwinjue I've looked at all the changes and everything looks great! Would it be possible to change "Los Angelenos" to "Angelenos" on the About page? It's the third word in the beginning of the paragraph. Thanks, everyone so so much for all the help with these issues!

**Comment by mc759** [comment]
Hey @edwinjue and @melissahermes99, Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
