### ISSUE TITLE
[EPIC] Data Science Analytics Dashboard (Reports) H1 2023

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1378]
### Summary
This epic will keep track of issues related to the development of the [Analytics Dashboard](https://dev.311-data.org/reports/dashboards/overview_combined) for the v2 launch.  

### Required Issues 
- [x] Analytics Dashboard -  https://github.com/hackforla/311-data/issues/699
- [x] Analytics Dashboard - Descriptive and diagnostic statistics (#1197)
- [ ] #1495 
- [ ] #1468

### After v2
- [ ] Analytics Dashboard - Advanced statistics 
- [ ] Analytics Dashboard - YoY and MoM Trends (#1228)

### Related Bugs / Legacy Issues
- #1233 
- #1234 
- #1235 
- #1246 
- #1354

**Comment by EchoProject** [comment]
Need to link all existing issues related to the analytics dashboard to this epic.

**Comment by EchoProject** [comment]
Hi Team! @joshuayhwu @susanklm 
When you have time, please do the following:  
- [ ] Link existing design issues related to the Analytics Dashboard to the Required Issues section 
- [ ] IF an issue is complete, please check mark it here, and close that issue with a comment. 
- [ ] Link THIS epic to each of those issues in the Resources section, please. 
- [ ] Take an inventory of issues that don't fall into any of the DS team epics. 
- [ ] Let me know if you have any questions. 

Thanks!

**Comment by joshuayhwu** [comment]
Inventory of non-epics:
- #184 
- #239 
- #438 
- #791 
- #802 

Non-Epic but related:
- #1259

**Comment by joshuayhwu** [comment]
Met with design team in August and we reached a consensus that UI/optimization is only possible with downstream user feedback. For now, it's mostly just maintaining color consistency with the rest of the website.

**Comment by joshuayhwu** [comment]
Dashboard successfully integrated to website. Will discuss with UI/UX regarding other optimizations.

**Comment by sanjumv** [comment]
@ryanfchase Closing this epic for v2 and can be used for reference.
Per conversation with Ryan, @mru-hub and @chelseybeck 311 data will not be maintaining a Data Science team and will refer to Data Science CoP for their contribution to our project.
