### ISSUE TITLE
[EPIC] UI/UX Design Map Page H1 2023

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1380]
### Overview
This epic will keep track of all design work related to the [map page](https://dev.311-data.org/map) required for the H1 2023 roadmap. 

### Required Issues 
- [ ] Menu Redesign 
- [x] https://github.com/hackforla/311-data/issues/1284 
- [ ] https://github.com/hackforla/311-data/issues/1305
- [x] https://github.com/hackforla/311-data/issues/1126
- [x] https://github.com/hackforla/311-data/issues/1147 
- [ ] https://github.com/hackforla/311-data/issues/1319
- [x] https://github.com/hackforla/311-data/issues/1300
- [x] https://github.com/hackforla/311-data/issues/1400#issue-1406970376
- [ ] https://github.com/hackforla/311-data-archive/issues/1128

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by EchoProject** [comment]
Add all design issue links to the required issues list.

**Comment by EchoProject** [comment]
Hi Team! @melissahermes99 @elizabeth-ux 
When you have time, please do the following:  
- [ ] Link existing design issues related to the Map page to the Required Issues section 
- [ ] IF an issue is complete, please check mark it here, and close that issue with a comment. 
- [ ] Link THIS epic to each of those issues in the Resources section, please. 
- [ ] Take an inventory of issues that don't fall into any of the Design team epics. 
- [ ] Let me know if you have any questions. 

Thanks!

**Comment by sanjumv** [comment]
@ryanfchase @elizabeth-ux Closing this epic and moving its issues to functionality based epics
