### ISSUE TITLE
[EPIC] UI/UX Design Navigation & Content Pages H1 2023

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1395]
### Overview
This epic will keep track of all design work related to the navigation and content related work required for the H1 2023 roadmap.

### Required Issues 
- [x] https://github.com/hackforla/311-data/issues/1297#issue-1318665292
- [x] [Top Navigation Highlight ](https://github.com/hackforla/311-data/issues/1147)
- [x] https://github.com/hackforla/311-data/issues/1347 
- [ ] FAQ Layout Re-design 
- [ ] https://github.com/hackforla/311-data/issues/1160
- [x] https://github.com/hackforla/311-data/issues/1260
- [ ] https://github.com/hackforla/311-data/issues/1458
- [x] https://github.com/hackforla/311-data/issues/1297#issue-1318665292
- [ ] https://github.com/hackforla/311-data/issues/1112#issue-924403251

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by EchoProject** [comment]
Hi Team! @melissahermes99 @elizabeth-ux 
When you have time, please do the following:  
- [ ] Link existing design issues related to Navigation and Content pages to the Required Issues section 
- [ ] IF an issue is complete, please checkmark it here and close that issue with a comment. 
- [ ] Link THIS epic to each of those issues in the Resources section, please. 
- [ ] Take an inventory of issues that don't fall into any of the Design team epics. 
- [ ] Let me know if you have any questions. 

Thanks!

**Comment by mc759** [comment]
@elizabeth-ux and @melissahermes99, I notice that issue 1147 is closed by not checked off on this epic ("Top navigation highlight"). Just want to confirm there is nothing i am missing regarding this issue before checking it off the list.

Thanks!

**Comment by melissahermes99** [comment]
@mc759 

Issue 1147 has been made into a new issue, [1401](https://github.com/hackforla/311-data/issues/1401). It should be checked off here because it is now an issue for frontend. As for the FAQ page redesign, I'll go ahead and create an issue.

**Comment by sanjumv** [comment]
@ryanfchase Could you check with the design team and update on the issue.
