### ISSUE TITLE
Recruiting Team Members for 311-Data

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1410]
### Overview
We need to track team recruitment so that we maintain a minimum headcount to keep the project thriving. 

### Action Items 
Copy this list into a comment to track recruiting 
- [ ] Click Open Roles Board for the required function (links below) 
- [ ] Find a relevant 311-data "Card" from the "filled" column 
- [ ] Drag the Card to the appropriate role column 
- [ ] Make edits to the card as needed 
- [ ] Once the role/s have been filled, mo

### Resources/Instructions
[Engineering Open Roles Board](https://github.com/hackforla/engineering/projects/2) 
[Data Science Open Roles Board](https://github.com/hackforla/data-science/projects/2)
[UI/UX Open Roles Board](https://github.com/hackforla/UI-UX/projects/7) Includes Design, Resarch, and Writing
[Product Management Open Roles Board](https://github.com/hackforla/product-management/projects/8)

**Comment by HiGregory** [comment]
Hi @EchoProject, 

We are supporting a similar initiative in Miami and Baltimore. 

Wanted to know if there is room for collaborating and comparing notes for other cities doing 311 data projects.

For example, if our team of Data Specialists wants to support LA tasks.

**Comment by EchoProject** [comment]
Note to review recruiting needs by the end of January. 

- [ ] Product 
- [ ] Project 
- [ ] SWE 
- [ ] Design 
- [ ] Research 
- [ ] Data Science
