### ISSUE TITLE
[EPIC] Product Management H1 2023

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1422]
### Overview
This epic will track Product, Project, and Admin tasks related to H1 2023 OKRs. Product managers ensure the team is focused on the most important issues during a given planning period. 

### Required Issues 
**Product Management** 
- [x] Planning H1 2023 
    - [x] Create OKR slides 
    - [x] Create roadmap slides   
- [ ] Relationship with City #1287 
- [ ] Build contact list with NCs 
- [ ] Success Metrics #710

**Project Management** 
- [ ] Create H1 2023 epics for each key area 
    - [x] Eng - Map  #1396 
    - [x] Eng - Ops Migration #1367 
    - [ ] Eng - URL Book Marking 
    - [x] Data Science - Analytics Dashboard #1378 
    - [x] Data Science - Research #1291 
    - [x] Data Science - Product & Business Analytics #1378 
    - [x] Design - Menu Redesign #1380 
    - [x] Design - Design System #1395 
    - [x] Research - Testing (Alpha, Beta, Usability)  #1332  
- [x] Update Milestones to reflect epics (use milestone label to link issues to epic) 
- [ ] Maintain Missing Labels #1134 - Create a new issue for 2023 
 
**Admin Management** 
- [ ] Onboarding videos 
    - [x] Project board overview and process 
    - [ ] System architecture 
    - [ ] Data Science research process 
    - [ ] Data Analyst tooling  
- [ ] Update Wiki #1056 
- [ ] #1475
- [ ] Create a resource sheet with key PM docs

### Resources/Instructions
REPLACE THIS TEXT -If there is a website that has documentation that helps with this issue provide the link(s) here.
