### ISSUE TITLE
[EPIC] Product/ Business Data Analytics

### ISSUE THREAD

**Issue by mc759** [hackforla/311-data#1450]

**Comment by ajmachado42** [comment]
### Overview
To create product / business analytics on the 311-data.org site. User analytics, etc. This is a general outline, to be groomed up with more discussion between PMs, engineering, and data science. 

### Action Items

- [ ] Create property in Google Analytics (GA) from domain email (need to confirm which one)
- [ ] Sync with developers on getting the property ID into the front end of the website
- [ ] After GA is connected, determine which metrics are most useful with PMs
- [ ] etc.?

### Resources/Instructions
https://github.com/hackforla/311-data/issues/1450

**Comment by ajmachado42** [comment]
@EchoProject @susanklm @joshuayhwu @mc759 I added some details here from the convo in Slack. Do we know which engineer would be best to be tagged on this to work with Susan?

**Comment by susanklm** [comment]
Here is the email/account of our GA: 311-Data@hackforla.org. The property of the account is 311-data.org.

**Comment by sanjumv** [comment]
@ryanfchase This issue is not part of v2 and therefore going to be closed and may be future reference.
