### ISSUE TITLE
[EPIC] Competitive Analysis of Data Visualization Sites

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1483]
### Dependencies 
- [ ] #1520 
- [ ] #1521 
- [ ] #1522 
- [ ] #1523 
- [ ] #1524 

### Overview
This is an epic that organizes all parts of the competitive analysis of data visualization sites. Each site has its own issue that includes all the features to be covered in the competitive audit. 

### Details
Getting an understanding of how different sites showcase data through a comparison of sites that offer similar data visualization features. The project will be focused on the frontend look of the site including how data is presented through charts and map features. We hope the end result will be useful to the team in creating data visuals that can provide value for our users. 

### Developing Research Plan
- [x] Brainstorm research plan 
- [x] Create a list of similar sites for research/reference
- [x] Validate the needs of the research project
- [x] Create a research plan 
- [x] Decide on deliverables that will be most helpful 
- [x] Select sites that will be evaluated alongside criteria

### Organizing the Competitive Audit
- [ ] #1520
- [ ] #1521
- [ ] #1522
- [ ] #1523
- [ ] #1524

### Presentation
- [ ] Analyze insights from the completed research
- [ ] Develop presentation 
- [ ] Present to the 311 Data team for actionable insights on feature development

### Resources/Instructions
As you go through each site, check off boxes to demonstrate your progress on the competitive audit.

**Comment by sanjumv** [comment]
@ryanfchase @hworthen This issue is complete and closed.
