### ISSUE TITLE
Data for Dashboard

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1495]
### Overview
The simplified dashboard involves four graphs that each provide immediate value for our neighborhood councils. Our data science team has worked on code here that sets the groundwork for the data analysis that provides the greatest value for NC members. We have decided on two filters: neighborhood council and time frame (30, 90, 180 and 360 days). 

The data analysis [code](https://colab.research.google.com/drive/1Oo5f3Htu4n27J190wko0joXCBO1mLoNH?usp=sharing) has already been written. The main support we need is a few tweaks to help contextualize the data.

These are the data insights that would be the most useful for the Neighborhood Council (NC) User Persona. These are the data trends that we believe would be most useful for users. We hope to look at data from the "past month", "past 3 months", "past 6 months" and "past year" as our four options for analysis. We also hope to have a selection for each Neighborhood Council. Filter the raw 311 data frame for the aforementioned time periods and create 4 separate data frame for each timeframe. For each of the 4 dataframes, loop through each neighborhood council to conduct the analysis.

### Action Items

**Neighborhood Council by Time Frame**
- [ ] **Neighborhood Council - Ticket Composition** (NC x Time Frame x Ticket Percentages) #1499 
   - [ ] Pie Chart
- [ ] **Neighborhood Council - Most Frequent Tickets** (NC x Time Frame x # of Tickets organized by amount) #1500 
   - [ ] Bar Chart 
- [ ] **Neighborhood Council - Ticket Closing Timeframe Comparison** (NC x Time Frame x NC Average Time to Close a Ticket x LA Average Time to Close a Ticket) #1501 
   - [ ] Box and Whisker Chart
- [ ] **Neighborhood Council - Agencies Involved Composition** (NC x Time Frame x Agency Required) #1502 
   - [ ] Pie Chart or Bar Chart (From Greatest to Least) 

**In a Future Iteration**
- [ ] Neighborhood Council - Number of Open Tickets (NC x Time Frame x My NC Open Tickets)

**Filter Type - Specific**
- [ ] Neighborhood Council - Ticket Frequency change (NC x Time Frame x Selected Ticket Type x Selected Ticket Type Change in Frequency over Time)

### Resources/Instructions
See [Neighborhood Council User Persona](https://docs.google.com/document/d/1KGgCqIFHgYsqcVJQ5VqfFA-Us4e6i_8fdDVJ9cRNcqE/edit) for an idea of what the ideal persona looks like
See [Neighborhood Council User Journey](https://docs.google.com/document/d/1LfOwbnyyxEZhOenZpuWgUPQXoZHUbA4Djstv1VTwuN0/edit) to see what the rationalization behind the user journey and what maps they would want to see on the data dashboard
#1487 - Plot.ly Design Feature Inventory

**Comment by joshuayhwu** [comment]
[Code](https://colab.research.google.com/drive/1Oo5f3Htu4n27J190wko0joXCBO1mLoNH?usp=sharing) to address all items except the Ticket Frequency change as that will depend on the time range we want to compare.

**Comment by SophAm1** [comment]
@joshuayhwu Great job! I wanted to see if the average time to close a ticket across all neighborhood councils was available as data? And are we able to get an idea of the composition of involved agencies (percentage) for each NC?

**Comment by hworthen** [comment]
I renamed this because it is about data for the dashboard, not about user personas.  Am creating a new issue for user personas now.
