### ISSUE TITLE
[EPIC] Data Dashboard V2

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1503]
### Dependency
- [ ] #1499
- [ ] #1500
- [ ] #1501
- [ ] #1502
- [ ] #1506 

### Overview
We need to simplify the dashboard, to make the dashboard graphs easier to understand and reduce noise (extra graphs that don't mean anything), for the end users.  This issue is the epic that makes all the issue needed to achieve that.

### Details
The simplified dashboard involves four graphs that each provide immediate value for our neighborhood councils. Our data science team has worked on code here that sets the groundwork for the data analysis that provides the greatest value for NC members. We have decided on two filters: neighborhood council and time frame (30, 90, 180 and 360 days). 

The data analysis [code](https://colab.research.google.com/drive/1Oo5f3Htu4n27J190wko0joXCBO1mLoNH?usp=sharing) has already been written. The main support we need is a few tweaks to help contextualize the data.

These are the data trends that we believe would be most useful for users. We also hope to have a selection for each Neighborhood CouncilWe hope to look at data from the "past month", "past 3 months", "past 6 months" and "past year" as our four options for analysis. Filter the raw 311 data frame for the aforementioned time periods and create 4 separate data frame for each timeframe. For each of the 4 dataframes, loop through each neighborhood council to conduct the analysis.

### Create Issues 

- [x] Neighborhood Council - Ticket Composition (Pie Chart) #1499 
- [x] Neighborhood Council - Most Frequent Tickets (Bar Graph) #1500 
- [x] Neighborhood Council - Ticket Closing Timeframe Comparison (Box and Whisker) #1501 
- [x] Neighborhood Council - Agencies Involved (Bar Graph or Pie Chart) #1502 

### Rewriting the Issues to Meet Data Science Guidelines
- [ ] #1499 
- [ ] #1500 
- [ ] #1501 
- [ ] #1502 

### Having Sample Charts for The Issues 
- [ ] #1506 

### Resources/Instructions
See [Neighborhood Council User Persona](https://docs.google.com/document/d/1KGgCqIFHgYsqcVJQ5VqfFA-Us4e6i_8fdDVJ9cRNcqE/edit) for an idea of what the ideal persona looks like
See [Neighborhood Council User Journey](https://docs.google.com/document/d/1LfOwbnyyxEZhOenZpuWgUPQXoZHUbA4Djstv1VTwuN0/edit) to see what the rationalization behind the user journey and what maps they would want to see on the data dashboard
#1487 - Plot.ly Design Feature Inventory
[How to Write an Issue for a Data Scientist 
](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-a-Data-Scientist)

**Comment by ryanfchase** [comment]
Reviewing issues on this epic. Keeping it open seeing as this feature is still not completed.
