### ISSUE TITLE
Request for Sample Charts for Data Science Research Analysis 

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1506]
### Dependencies
- [x] #1519 
- [x] #1518 
- [x] #1517 
- [x] #1516 

### Overview
Creating very simple chart designs to help illustrate the types of charts we want to see on the data dashboard with a focus on functionality, simplicity and clear storytelling. 

### Details 
Specifically, we are looking for a sample design of charts that display ticketing request data in a meaningful and digestible way. This could include bar charts, line charts, pie charts, box-and-whisker and other types of visualizations that you believe would be effective in conveying the data. Emphasis on chart design and labels over color schema. 

### Action Items

- [x] {Ready for a Design Lead to incorporate decisions including workspace into this issue}
- [x] Review the GitHub Issue #1503 to understand the scope of the project
- [x] Look at each of the data science issues outlined in the issue 
- [ ] Familiarize yourself with the datasets that will be used for each project including the structure, the types of variables included, and other relevant information to be included
- [x] Determine the appropriate chart types for each project based on research questions and the data
- [ ] Determine the appropriate labels and titles for each chart
- [x] Creates issues for each chart type 
   - [x] Ticket Composition Graph #1519 
   - [x] Most Frequent Tickets in a NC #1518 
   - [x] Tickets Closing Timeframe Comparison #1516 
   - [x] Agencies Involved Composition #1517 
- [ ] Document the design process and decisions made, and submit the sample charts to the GitHub for review 
   - [ ] Ticket Composition Graph #1519 
   - [ ] Most Frequent Tickets in a NC #1518  
   - [ ] Ticket Closing Timeframe Comparison #1516 
   - [ ] Agencies Involved Composition #1517 
- [ ] Release dependency on #1503 

### Resources/Instructions
[Creating an Effective Issue ](https://github.com/hackforla/311-data/wiki/How-to-Create-Issues)
[How to Write an Issue for Designers](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-a-UI-UX-Designer)
[Example Charts](https://docs.google.com/presentation/d/1Go9L5p_aIlZh-AJ3G0kPwGAeZapiyr4TBF-IdfHa33k/edit#slide=id.p)
