### ISSUE TITLE
[EPIC] Feature Audit for 311 Data Site Content

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1513]
### Overview
We want to get an idea of how to clean up the writing and formatting on our content pages in anticipation of product release so that we can hit the ground running. 

### Details
Our objective: We want to improve the content of site pages and improve how the site is structured. We will be focusing on three primary content pages: the FAQ page, the About Page and the Privacy Page.

### Product Management
- [x] Identify the features included in the audit
- [x] Identify the pages to be covered of the audit
- [ ] Identify pain points in current issues 
   - [ ] Identify the criteria for good writing
   - [ ] Identify the criteria for good formatting (bolding, hyperlinks, etc)
   - [ ] Identify the criteria for good organization (category, order, etc)
- [ ] Create issues for the future
- [ ] Prepare insights for the next steps to clean the site pages  
- [ ] Use this to develop a strategy for updating content pages 

### Create an Issue for an Audit of Every Content Page on the Site
- [ ] FAQ Page - Feature Audit
  - [ ] Outline key design elements to be covered
  - [ ] Outline key formatting elements to be covered 
  - [ ] Outline key organizational elements to be covered
- [ ] About Page - Feature Audit
  - [ ] Outline key design elements to be covered
  - [ ] Outline key formatting elements to be covered
  - [ ] Outline key organizational elements to be covered
- [ ] Privacy Page - Feature Audit
  - [ ] Outline key design elements to be covered
  - [ ] Outline key formatting elements to be covered
  - [ ] Outline key organization elements to be covered 

### Resources/Instructions
https://www.mindmesh.com/glossary/what-is-feature-audit

**Comment by sanjumv** [comment]
@ryanfchase @Graemo27 Closing this epic and creating new issues based on Graem's audit. Moving its issues to functionality based epics.
