### ISSUE TITLE
Bring all sidebar filters together

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#157]
### Overview
This ticket will connect all the ui components in the sidebar so that they can be used from the visualizations.

### Action Items
- [x] Have start date(Date selector component #154 ) and end date (Date selector component #154)
  - [ ] Trigger console.log (or more if ambitious) from the root app.js or what ever component we are calling the parent, on any change from either component
- [x] Have the neighborhood council selection and a callback/event for any (de)selection (#155)
- [ ] Have request type selection and a callback/event for any (de)selection (#156)
- [ ] Include the Submit button that will emit _all_ of the filters from the above selections
  - For now, this will be the event used to update the visulizations
  - Later, UI will be updated in the events emitted by the components themselves #154 #155 #156

### Resources/Instructions
See [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=16%3A4) mock for reference

**Comment by johnr54321** [comment]
ETA Tuesday 3/3/2020.
