### ISSUE TITLE
WIP: Onboard & Offboard: UI/UX

### ISSUE THREAD

**Issue by Graemo27** [hackforla/311-data#1580]
### TODO
- this is a copy of the Product Onboarding issue. It is being currently edited

### Dependency
The need to onboard/offboard a new person

### Overview
We need to have a checklist of items to do when a UI/UX Designer onboards and offboards so that the process can be consistent and fast.

### Date Updated
Created: 2023-09-13
Updated: 2023-09-13

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

**Comment by ryanfchase** [comment]
#### Onboard Angela Wu 10-11-23
- [ ] Slack channel membership
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Train how to 
   - [ ] open 311-data Figma page

**Comment by ryanfchase** [comment]
#### Onboard Allison Jeon 10-11-23
- [ ] Slack channel membership
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Train how to 
   - [ ] open 311-data Figma page

**Comment by ryanfchase** [comment]
#### Onboard Luan Nguyen 10-11-2023
- [ ] Slack channel membership
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Train how to 
   - [ ] open 311-data Figma page

**Comment by ryanfchase** [comment]
#### Onboard Paul Kim 2023-10-11
- [ ] Slack channel membership
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Train how to 
   - [ ] open 311-data Figma page

**Comment by ryanfchase** [comment]
#### Onboard Shu 2023-10-11
- [ ] Slack channel membership
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Train how to 
   - [ ] open 311-data Figma page

**Comment by Joy-Truex** [comment]
#### Onboard Gillian Terzis 01-26-25
- [ ] Slack channel membership
  - [ ] `#311-data`
  - [ ] `#311-data-uiux`
- [ ] Google Drive (could ask PM to do this)
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub (send PM new joiner's Github ID)
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] 311 Figma Page
  - [ ] invite them by email (don't just share link)
  - [ ] modify their permissions to `can edit`

<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: UX/UI Designer
- Dashboard: M (representing "member". Required)
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="254">

</p>
</details>

**Comment by Joy-Truex** [comment]
#### Onboard Dana Choe 1-29-25
- [ ] Slack channel membership
  - [ ] `#311-data`
  - [ ] `#311-data-uiux`
- [ ] Google Drive (could ask PM to do this)
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub (send PM new joiner's Github ID)
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] 311 Figma Page
  - [ ] invite them by email (don't just share link)
  - [ ] modify their permissions to `can edit`

<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: UX/UI Designer
- Dashboard: M (representing "member". Required)
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="254">

</p>
</details>

**Comment by Joy-Truex** [comment]
#### Offboard Gillian Terzis
- [ ] Remove from Google calendar invite
   - You need to log into the 311-data@hackforla.org account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the 311 Data project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Wednesday All-Team meeting (ad-hoc)
   - [ ] Thursday PM meeting
- [ ] Google Drive Permissions
   - [ ] demote access from Contributor to Viewer in 311 Data folder
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues)
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki]

**Comment by Joy-Truex** [comment]
#### Onboard Jessie Liu
- [ ] Slack channel membership
  - [ ] `#311-data`
  - [ ] `#311-data-uiux`
- [ ] Google Drive (could ask PM to do this)
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster (On Google Drive)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub (send PM new joiner's Github ID)
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github
- [ ] Update team page on Wiki (Can only do after Roster)
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/311-data/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] 311 Figma Page
  - [ ] invite them by email (don't just share link)
  - [ ] modify their permissions to `can edit`

<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: UX/UI Designer
- Dashboard: M (representing "member". Required)
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="254">

</p>
</details>
