### ISSUE TITLE
Update Map milestone to include checklist

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1613]
### Overview
We need to add a checklist of deliverables/components (visuals and behaviors) to the Map milestone so that everyone knows what needs to be completed for the V1.2 launch. To do this, we'll work off Sanju's groundwork document and adjust as necessary to meet current/foreseen/evolving needs. 

### Action Items
- [x] Draft up checklist described above as a comment in this issue.
- [x] Obtain at least one review on your checklist from another PM 
- [x] Update the description of the Map milestone with your description.

### Resources/Instructions
Groundwork for the project [use this as a starting point to inform checklist]: https://docs.google.com/document/d/1aQqAn_OOBZhpyHZcAklTqgdH8SDWAMmDep12v64k324/edit?usp=sharing

Product requirements doc [may be helpful to review historical docs like this one]: https://docs.google.com/document/d/160Pp-Arhv8l46t66f5DLGiC5nkiSxHQq3fZbFYjVE5g/edit?usp=sharing 

Map feature complexity [may give us a better understanding of prioritizing components of map page]: https://docs.google.com/spreadsheets/d/1vkdwIGSkIhbgOUs7THdDxOvW8NxxLMrBUK6MJ2WOeic/edit?usp=sharing

**Comment by annaseulgi** [comment]
Hi all, would everyone be open to considering removing the "Get shareable link" from the MVP list? I believe the previous/current design team didn't contribute to the button so we also don't have a design in the Figma or rationale for the design choice.

**Comment by ahmedsalah0130** [comment]
This checklist is for the Map Milestone for V1.2 

1. Neighborhood Council Boundaries
2. View the neighborhood as a whole when single-clicked (Unfocus on click-out)
3. Hover over data points for summary information
4. Loading Modal with About Info

**Comment by ryanfchase** [comment]
Legend

Selectable district 
District Search (Singular) 
Selectable time range 
Selectable request type
Select/Deselect All
Individual SelectRequest Status
Open, All, Closed
Default Values?
Request Status: Open
All Request Types
Previous 7 Days (current week)
No Boundaries
Get Shareable Link
Maximize / Minimize Button
