### ISSUE TITLE
Epic: Change map color scheme to light mode

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1618]
# Design To Engineering Hand Off

### Overview
We need to change the design/color of the map background to more easily see pins/differentiation.

### Description of Requested Change

We'd like to make the map background to a lighter color to make it easier to see the pins.

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees (Design Lead, Engineering Lead, Assigned PM)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Map: Light Version

### Screenshot of Finalized Designs

<details><summary>Screenshot of Figma</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/140572118/89b86183-e519-4346-bb8a-9fb7b3131b3a)

</p>
</details> 

### Design Issue(s)

- #1601 - Map Redesign Updates for V1.2

# Engineering

### Engineering Action Items
- [x] Review 'Useful Notes for Figma' below
- [x] Locate section on 311 Data Figma
- [x] Create and list engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

- https://github.com/hackforla/311-data/issues/1661

### Resources

- [MapBox docs on map styles](https://docs.mapbox.com/api/maps/styles/)

**Comment by ryanfchase** [comment]
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime.

**Comment by ryanfchase** [comment]
PM Instructions for correcting Design to Engineering Hand Off tickets to become Epics:

- [ ] Preface title with "Epic: "
- [ ] Update overview to comply with format, `We need X for Y reason` (consider using text from Description of Requested Change)
- [ ] Make sure labels indicate who should be working on this ticket next (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))
- [ ] If Milestone was set to `Launch`, set it to `Map Page` or `Product Maintenance`.
- [ ] Modify the screenshot to use the Details command to make it hideable (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))

**Comment by ryanfchase** [comment]
More info needed from dev team. Leaving as `draft`.

**Comment by ryanfchase** [comment]
Hi @annaseulgi and design team -- @Skydodle implemented a prototype version of the light basemap and boundary color -- after reviewing the work needed to implement the designs on Figma, we've come up with a couple of points to address:

- We noted that the figma section on `Map: Light Version` includes boundaries for all of LA County. Adding all county boundaries is not part of the requested changes, we will disregard this aspect of the design
- We're noticing that this light basemap's mountains and terrain is different than the Figma. I think dev is limited here to what Mapbox can provide as pre-determined basemaps. Please review the "Comparing Mapbox Light v8 thru v11" dropdown below
- Dev wants to know what the on-hover design should be for the light mode map (while the map is not focused on a particular NC) -- will it be `#62ADFC`, per the reference?
- Dev wants to confirm that while focusing on an NC should the other NC boundaries still be drawn? (See "NC On-Focus Boundaries" dropdown)

<details><summary>@Skydodle's prototype</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/0f6c1599-7631-488a-9ef1-d390c0e69387)

</p>
</details> 

<details><summary>Image: Light Version includes LA County boundaries</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/2f530aeb-6ef2-4747-b097-04aa798ffcfe)

</p>
</details> 

<details><summary>NC On-Focus Boundaries</summary>
<p>

Boundaries for non-focused NCs (as pictured in Figma)
![image](https://github.com/hackforla/311-data/assets/6414668/26a6423f-0739-40d7-bb19-b25bb3523e20)

Boundaries for non-focused NC's are missing (pictured by prototype)
![image](https://github.com/hackforla/311-data/assets/6414668/a128c39f-da4e-4970-9625-0eaad92d2fa0)

</p>
</details> 


<details><summary>Comparing Mapbox Light v8 thru v11</summary>
<p>

v8
![image](https://github.com/hackforla/311-data/assets/6414668/1d9da29a-b7e8-4c80-affe-e01f17bc1774)

v9
![image](https://github.com/hackforla/311-data/assets/6414668/e13f4f80-b30f-4f2f-8c42-93df1e6c6028)

v10
![image](https://github.com/hackforla/311-data/assets/6414668/a21008fd-d984-4e1c-b2af-1b91e2679db1)

v11
![image](https://github.com/hackforla/311-data/assets/6414668/b1df0bff-fd2e-4e57-b0d7-7fd7d403c202)



</p>
</details> 

Thanks! Let us know if you need any clarification on these questions!! cc @edwinjue

**Comment by annaseulgi** [comment]
1. Please ignore the other areas. It was included in a vector I found for LA County but it was unintentional to include those regions.
2. Are v11 contrast levels set or are they adjustable in mapbox? Ideally, it would be good to have higher contrast levels (such as v9) without the terrain because it can be distracting.
3. Can we get some clarification on this question?
4. While a user is viewing a specific neighborhood district, it may be good to have thinner lines outlining the other ND in the area with potentially a lower opacity of the lines/outlines (if possible). Please follow up regarding this & if design will need to provide a mockup of this.

Thanks all, @ryanfchase @Skydodle @edwinjue !

**Comment by ryanfchase** [comment]
Hi @annaseulgi thanks for the responses! Ya lemme clarify on your follow ups

> Are v11 contrast levels set or are they adjustable in mapbox? Ideally, it would be good to have higher contrast levels (such as v9) without the terrain because it can be distracting

I would say the pre-defined contrast levels for basemaps are **not** adjustable. If v9 has the best contrast, we should use that one as a pre-launch style. In the future, I think we could experiment with building custom map styles in Mapbox. I was just tinkering around with [this tutorial](https://docs.mapbox.com/studio-manual/reference/styles/#hillshade-layer) on creating a basemap with custom hillshade styles.

> Can we get some clarification on this question?

Sure! For example, when you hover over an NC, we are getting a grey fill color within the boundary. While we're implementing light mode with the, should we use the blue fill color for the hovered NC? See pictures below...

<details><summary>Screenshot of current NC hover</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/9d349c13-e17b-4b75-b64f-13bc8f60df91)


</p>
</details> 

<details><summary>Screenshot of NC hover (@funbunch's proposed implementation)</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/3441200/f6c5254a-3400-417a-bd0b-a24acc08f80a)

</p>
</details>

**Comment by annaseulgi** [comment]
@ryanfchase thanks for the clarification - the blue fill with the opacity looks good but I'll discuss it with the design team and get back to yall on this (@funbunch )

**Comment by annaseulgi** [comment]
@ryanfchase @funbunch  Hi all, let's go with the proposed implementation following the same color and opacity :). Thank you!

**Comment by ryanfchase** [comment]
PMs are closing this as done!
