### ISSUE TITLE
Epic: Update Loading Screen With 311 Data Info

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1620]
# Design To Engineering Hand Off Epic

### Overview
We need to update the loading modal so that it is clear that the website is for the 311 Data project and has no affiliation with the City of LA.

#### Details

Bonnie has asked that the loading modal combines the loading popup with the "non-affiliation message" popup. She also suggested that the user can be presented with fun-facts while the user waits for the data to load.

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees (Design Lead, Engineering Lead, Assigned PM)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

NOTE: Bonnie has requested an update to the design of the loading modal. Design Team needs to update these designs on the Figma.

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Loading Screen

### Screenshot of Finalized Designs

<details><summary>Screenshot of Figma</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/140572118/ccb22039-3487-4f27-8631-eedd6158064d)

</p>
</details> 

### Design Issue(s)

- #1604 
- #1594 
- #1609 
- https://github.com/hackforla/311-data/issues/1655

# Engineering

### Engineering Action Items
- [ ] Review 'Useful Notes for Figma' below
- [ ] Locate section on 311 Data Figma
- [ ] Create and list engineering tickets, adding dependency on design tickets if they are not yet completed.

### Final Action items for PM
- [ ] Review all changes to confirm this epic is complete
- [ ] Close this issue

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

- https://github.com/hackforla/311-data/issues/1676

### Resources
What is a Design, Engineering Handoff epic: Ticket for tracking designs submitted to engineering, discussion around implementation of designs
```
Replace this text with a bulletted list of resources that might be useful to engineers or designers
```

**Comment by edwinjue** [comment]
Hi @annaseulgi, just want to make sure I'm looking at the most up-to-date version of this file. Can you provide a link to the figma file and a screenshot of where it is on the page? Thanks

**Comment by annaseulgi** [comment]
@edwinjue All the up-to-date figma designs and link to the file are located above in the issue. Please refer to that for specifications. Thanks!

**Comment by ryanfchase** [comment]
I think I'm going to change this to `role: UI/UX Design` because, per conversation [here](https://github.com/hackforla/311-data/issues/1545#issuecomment-1896450926), UIUX will need to draft up a new version of the modal per Bonnie's suggestion. Engineering will have to wait until these new designs are ready.

@annaseulgi let me know if you think this is correct course of action!

**Comment by ryanfchase** [comment]
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime.

Also -- requirements have changed based on convo with Bonnie in previous general meeting. PM team to update requirements before moving back to Epic column.

**Comment by ryanfchase** [comment]
PM Instructions for correcting Design to Engineering Hand Off tickets to become Epics:

- [ ] Preface title with "Epic: "
- [ ] Update overview to comply with format, `We need X for Y reason` (consider using text from Description of Requested Change)
- [ ] Make sure labels indicate who should be working on this ticket next (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))
- [ ] If Milestone was set to `Launch`, set it to `Map Page` or `Product Maintenance`.
- [ ] Modify the screenshot to use the Details command to make it hideable (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))

**Comment by bberhane** [comment]
Is this good to close @ryanfchase?

**Comment by bberhane** [comment]
Yes, it is!
