### ISSUE TITLE
Epic: Update About Me [Civic Tech Structure Logo]

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1621]
# Design To Engineering Hand-Off

### Overview
We need to remove and replace the Code for America logo with the Civic Tech Structure logo so that website visitors know the correct organization this project is affiliated with. 

### Description of Requested Change

Remove the Code For America logo and replace it with the Civic Tech Structure logo.

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees (Design Lead, Engineering Lead, Assigned PM)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: About Me

### Screenshot of Finalized Designs

Image which helps engineer understand where to look. (Replace the url and remove the markdown tags)

<details><summary>Screenshot of Figma file</summary>
<p>

<img src="https://github.com/hackforla/311-data/assets/140572118/4640633e-aa77-4d78-8e3d-22a79b0f36c3" width="100%"/>

</p>
</details> 

### Design Issue(s)
- #1622 

# Engineering

### Engineering Action Items
- [x] Review 'Useful Notes for Figma' below
- [x] Locate section on 311 Data Figma
- [x] Create and list engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)
- https://github.com/hackforla/311-data/issues/1639

**Comment by annaseulgi** [comment]
Added 3 PMs, feel free to remove yourself!

**Comment by annaseulgi** [comment]
@ahmedsalah0130 here is the issue. I believe you made a  duplicate!

**Comment by ryanfchase** [comment]
I've created an engineering issue, #1621 and @traycn will begin when ready

**Comment by ryanfchase** [comment]
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime.

**Comment by ryanfchase** [comment]
PM Instructions for correcting Design to Engineering Hand Off tickets to become Epics:

- [ ] Preface title with "Epic: "
- [ ] Update overview to comply with format, `We need X for Y reason` (consider using text from Description of Requested Change)
- [ ] Make sure labels indicate who should be working on this ticket next (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))
- [ ] If Milestone was set to `Launch`, set it to `Map Page` or `Product Maintenance`.
- [ ] Modify the screenshot to use the Details command to make it hideable (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))

**Comment by bberhane** [comment]
Made corrections to comply with new standards

**Comment by ryanfchase** [comment]
Epic is looking good. Removing `ready for dev lead` and `role: Frontend` since the dev issue was provided

**Comment by ryanfchase** [comment]
Engineering team thinks this is done!

**Comment by ryanfchase** [comment]
PMs have checked the about page and the Civic Tech Structure logo is appearing as expected. Closing this Epic.
