### ISSUE TITLE
Epic: Updated Navigation (Removed Relevant Text Links)

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1624]
# Design To Engineering Hand Off

### Overview
We need to remove Research, Privacy, and Dashboard from the navbar menu because those links direct users to unmaintained portions of our app.

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees (Design Lead, Engineering Lead, Assigned PM)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Navigation

### Screenshot of Finalized Designs

<details><summary>Screenshot of new modal</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/140572118/9528c3c3-92ab-4084-bd96-ebc154c6b17c)

</p>
</details> 

### Design Issue(s)
- #1458 
- #1607 

# Engineering

### Engineering Action Items
- [x] Review 'Useful Notes for Figma' below
- [x] Locate section on 311 Data Figma
- [x] Create and list engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

- https://github.com/hackforla/311-data/issues/1654

### Resources

- n/a

**Comment by ryanfchase** [comment]
I think this can stay in Prio Backlog AS LONG AS the engineer who picks this up doesn't need additional clarification.

**Comment by funbunch** [comment]
@ryanfchase  This is what I have ready to do a PR for. I'll assign to myself

**Comment by Skydodle** [comment]
@funbunch @ryanfchase since Shannon picked up this issue, it should move to 'In Progress' now on the Project Board since she is now working on it? I clicked into this issue from the 'Priortized Backlog' thinking this is an issue available to be assigned.

**Comment by funbunch** [comment]
@Skydodle @ryanfchase Assuming this is just these 2 things right? 
Remove Research text link
Remove Privacy text link

**Comment by ryanfchase** [comment]
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime.

@funbunch I've also created an engineering issue: #1654, I'll open that ticket up and you can assign yourself while you work on that work. Will ping you once PMs are done making these tickets available.

**Comment by ryanfchase** [comment]
PM Instructions for correcting Design to Engineering Hand Off tickets to become Epics:

- [ ] Preface title with "Epic: "
- [ ] Update overview to comply with format, `We need X for Y reason` (consider using text from Description of Requested Change)
- [ ] Make sure labels indicate who should be working on this ticket next (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))
- [ ] If Milestone was set to `Launch`, set it to `Map Page` or `Product Maintenance`.
- [ ] Modify the screenshot to use the Details command to make it hideable (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))

**Comment by bberhane** [comment]
All menu items now direct to pages that are or will be active for launch.
