### ISSUE TITLE
Epic: Add Accessibility Modal

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1625]
# Design To Engineering Hand Off

### Overview
We need to add an accessibility modal onto the navbar because we need to explain how our app can be used with accessibility needs in mind

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees for next step only (e.g., Design Lead OR Engineering Lead)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Accessibility Modal

### Screenshot of Finalized Designs

<details><summary>Screencap of Figma</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/140572118/4750180d-a2cb-45f5-aad9-d833a8dca829)

</p>
</details> 

### Design Issue(s)
- https://github.com/hackforla/311-data/issues/1458

# Engineering

### Engineering Action Items
- [x] Review 'Useful Notes for Figma' below
- [x] Locate section on 311 Data Figma
- [x] Create and list engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

- https://github.com/hackforla/311-data/issues/1458

### Resources
```
Replace this text with a bulletted list of resources that might be useful to engineers or designers
```

**Comment by ryanfchase** [comment]
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime (it was moved earlier, but adding this comment for consistency)

**Comment by ryanfchase** [comment]
PM Instructions for correcting Design to Engineering Hand Off tickets to become Epics:

- [ ] Preface title with "Epic: "
- [ ] Update overview to comply with format, `We need X for Y reason` (consider using text from Description of Requested Change)
- [ ] Make sure labels indicate who should be working on this ticket next (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))
- [ ] If Milestone was set to `Launch`, set it to `Map Page` or `Product Maintenance`.
- [ ] Modify the screenshot to use the Details command to make it hideable (see instructions [here](https://github.com/hackforla/311-data/issues/1637#issuecomment-1902258565))

**Comment by ryanfchase** [comment]
We can move role missing because no team (design, frontend) needs to make adjustments to the ticket

**Comment by ryanfchase** [comment]
PMs have verified that the accessibility modal is working as requested. Closing this Epic.
