### ISSUE TITLE
Complete Action Steps Spreadsheet

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1649]
### Overview
We need to fill in Action Steps spreadsheet in order to create the remaining Pre-Launch issues and prioritize Post-Launch issues

### Action Items

For each post-launch item...
- [x] [RESEARCH] fill in the Action Steps (based on your suggestions from the [Bug Bash Usability Test](https://docs.google.com/presentation/d/1NBMnS8_znCnYNDNNQrN2Jh5GQZhZmX56rtHME-EewBY/edit#slide=id.p1))
- [x] [RESEARCH] fill in priority (High, Medium, or Low) based on your assessments
- [ ] [UIUX+ENG] fill in the Effort SP, reference our Story Point scale [here](https://github.com/hackforla/311-data/labels?q=size)
- [ ] [UIUX+ENG] if further discussion is required (e.g. feasibility, improvements on the Action Steps), skip the Effort SP and leave a note in the Notes column
- [ ] [PRODUCT] Calculate total SP to determine the "total amount of estimated time required"
- [ ] [PRODUCT] Review both SP Total and Priority, resolve any remaining discussion on each ticket
- [ ] [PRODUCT] Create tickets for Post-Launch items and assign them to milestones 

### Resources/Instructions
- Link to spreadsheet: [Action Steps post bug and usability testing January 2024](https://docs.google.com/spreadsheets/d/1y_8xUCxEU83adN2GjEIOt3F-wILJ1_c2KdgISFRN5cU/edit?usp=sharing)

### Background Info
- at the 2024-01-10 311 Data Weekly Meeting, research team demoed their bug bash results and suggestions
- per meeting discussion, research has identified 3 problems that are "must-do" as pre-launch items
  - Pop-up window (loading modal)
  - NC names fully written out in the search box
  - remove the shareable link button
- team needs to fill in info for the remaining 14 problems so we can understand how important each issue is and how difficult each one is to fix after the Launch milestone.

**Comment by ryanfchase** [comment]
@rrhea22 I've reviewed your work for `[RESEARCH] fill in priority (High, Medium, or Low) based on your assessments`, this is looking good!

When you're ready, please do the following
1. unassign yourself from this issue
2. remove label `role: UI/UX Research`
3. add label `role: UI/UX Design` and `ready for design lead`
4. move this card back into `Prioritized Backlog`

When you're done, please leave a comment tagging me -- thank you!

**Comment by annaseulgi** [comment]
@ryanfchase finished adding the SP for design - let me know if I need to do anything else

(note: my estimations may or may not be correct, I just ballparked how many hours I believe a task may take for the team)

**Comment by ryanfchase** [comment]
That's what we're looking for, thank you @annaseulgi !

**Comment by ryanfchase** [comment]
Action steps spreadsheet has been completed, closing this as done
