### ISSUE TITLE
Add Feedback For Users Requesting Unavailable Dates

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1680]
# Design To Engineering Hand Off

### Overview
We need to add feedback for when users attempt to access data that hasn't been loaded into the app so they aren't confused when nothing loads up on the screen

### Description of Requested Change

Per Bonnie's suggestion, we should implement the following
- disallow users from picking date ranges (e.g. years) where we do not have access to the data
- add an info button next to "Date Range" in the legend modal to display some messaging

1st Draft for messaging on Date Range info button:
```
311-Data is currently only able to load 311 service request data in 2024 and onwards. For updates on the release of available 311 Data, please follow our LinkedIn page at https://www.linkedin.com/company/hack-for-la/.
```

# Design

### Design Action Items
- [x] fill in 'Section Name' in Figma Resources
- [x] update image url and remove markdown tags
- [x] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Information Popover #1677

### Screenshot of Finalized Designs

Image which helps engineer understand where to look. (Paste image into Details section)

<details><summary>Screenshot of the Figma</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/140572118/3424eb98-ca93-4ae1-9881-486409515002)

</p>
</details> 

### Design Issue(s)
- https://github.com/hackforla/311-data/issues/1677

# Engineering

### Engineering Action Items
- [x] Review 'Useful Notes for Figma' below
- [x] Locate section on 311 Data Figma
- [x] Create and list engineering tickets
- [ ] Complete the engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

- https://github.com/hackforla/311-data/issues/1664
- #1696

**Comment by ryanfchase** [comment]
I copied over the suggested messaging for the proposed Date Range info button. I am calling it a 1st draft because I'm vaguely remember what Bonnie asked for -- this isn't verbatim what she told us to use. Very open to cleaning up the wording.

**Comment by annaseulgi** [comment]
@ryanfchase really quick - updated this issue for handing off designs even though I know we might change the process moving forward. just for communication purposes!

**Comment by Skydodle** [comment]
@annaseulgi @ryanfchase I've added the new dev ticket to this epic tracker under engineering issue:
- #1696

**Comment by bberhane** [comment]
Is this ticket good to close?

**Comment by ryanfchase** [comment]
Yes! I shall close it. Ty @bberhane
