### ISSUE TITLE
Improve Zoom Behavior on Map

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1700]
### Overview
We need to clarify the user's zoom controls, esp when selecting an NC so that they don't get confused when zooming in/out.

### Suggested Change from PMs

- We want to add a zoom control so that users can click on (+) to zoom in, and (-) to zoom out. Zooming in and out via scrolling should keep the same behavior (this is possibly just a note for dev).
- We want to "lock-in" the zoom level when user selects an NC, so that they can't scroll out too far or scroll away too far while an NC is selected. We can emphasize the "lock-in" by disabling the zoom-out control when an NC is selected

### Action Items

- [x] Address the problem overview with possible design solution(s) in a comment
- [x] Research potential solutions
- [x] Complete Design Iterations section below
- [x] Document user interaction in Figma

### PM Action Item

- [ ] Ensure information is transferred to this ticket: #1793
- [ ] make a dev ticket to limit panning when selection mode is on

### Resources

V1.2 Moderated Usability Test from October '23
- [slide indicating users get confused when scrolling out too far while in selection mode](https://docs.google.com/presentation/d/1NBMnS8_znCnYNDNNQrN2Jh5GQZhZmX56rtHME-EewBY/edit#slide=id.g29f7a872fc9_0_73)

---

### Design Iterations

**Please move ticket between `In Progress` and `In Review` to assist PM team**

<details><summary>Iteration 1</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1700#issuecomment-2138382290
- Added zoom in & out controls
- Suggested a "locked in" zoom level when a NC is selected
- Added indication that zooming is disabled by making the controls disappear when NC is selected
- Received feedback from design team for iteration 2

<img width="1644" alt="Screenshot 2024-05-29 at 3 44 07 PM" src="https://github.com/hackforla/311-data/assets/129242704/79f50b16-b2fd-4502-a917-aef0f0f9984e">

</p>
</details> 

<details><summary>Iteration 2</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1700#issuecomment-2168920133
- Changed colors of the zoom buttons for better accessibility
- Explored a popover feature that explicitly describes disabled status and how to enable zooming
- Exploring a change in the cursor to indicate a disabled status 

<img width="1596" alt="Screenshot 2024-06-14 at 4 43 34 PM" src="https://github.com/hackforla/311-data/assets/129242704/95edff5b-7e60-4d30-bbf5-ce970623882a">

</p>
</details> 

<details><summary>Iteration 3</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1700#issuecomment-2192835113
- Finalized cursor states after feedback
- Changed colors of popover for better consistency with design system

<img width="708" alt="Screenshot 2024-06-26 at 5 25 00 PM" src="https://github.com/hackforla/311-data/assets/129242704/06d62570-aa78-47d9-97d4-b53f2e46286e">

</p>
</details> 

<details><summary>Iteration 4</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1700#issuecomment-2193702141
- Modified design to make it a tooltip instead of popover
- Changed the position where tooltip would appear

<img width="863" alt="Screenshot 2024-06-28 at 3 48 34 PM" src="https://github.com/hackforla/311-data/assets/129242704/82e53c2f-740e-4793-a08b-2f995ee01be0">

</p>
</details> 

</p>
</details>

<details><summary>Final Iteration</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1700#issuecomment-2415394663

- Removed popup for disabled state
- Added in hover states
- Changed zoom button colors after adding in hover states for better visual design
- Zoom levels to be set according to Mapbox guidelines: https://github.com/hackforla/311-data/issues/1700#issuecomment-2392515315

![image](https://github.com/user-attachments/assets/dfbe1d90-4e80-4662-96a6-2b357ff588b5)

</p>
</details>
---

### Hand Off Materials

Figma Section Name: ⭐⭐⭐ Handoff

<details><summary>Before Screenshot</summary>
<p>

No NC Selected (no zoom controls present)
![image](https://github.com/hackforla/311-data/assets/6414668/c12279c6-c667-4153-876c-bfe2770a9916)

With NC Selected (no zoom controls present)
![image](https://github.com/hackforla/311-data/assets/6414668/f9d47392-7394-4443-83bf-9a754cc68077)

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

![image](https://github.com/user-attachments/assets/dfbe1d90-4e80-4662-96a6-2b357ff588b5)

</p>
</details> 

### Designer Resources

<details><summary>Iteration Dropdown Copy/Paste</summary>
<p>

```
<details><summary>Iteration X</summary>
<p>

Link to notes: `REPLACE WITH COMMENT URL`

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 
```

</p>
</details> 

<details><summary>Instructions for Engineering Hand Off</summary>
<p>

To Start Engineering Hand Off...
1. Ensure all Hand Off Materials are filled in
3. Add the "ready for dev lead" label
4. Leave a comment saying "This ticket is ready for engineering hand off." 

</p>
</details>

**Comment by Joy-Truex** [comment]
added "Research potential solutions" as an action step

**Comment by ryanfchase** [comment]
This ticket is ready for picking up @Joy-Truex @allisonjeon

**Comment by pogwon** [comment]
Iteration 1:

- Added zoom in & out controls
- Suggested a "locked in" zoom level when a NC is selected
- Added indication that zooming is disabled by making the controls disappear when NC is selected

<img width="1644" alt="Screenshot 2024-05-29 at 3 44 07 PM" src="https://github.com/hackforla/311-data/assets/129242704/79f50b16-b2fd-4502-a917-aef0f0f9984e">

**Comment by ryanfchase** [comment]
@pogwon please provide Iteration 2 if available -- otherwise an ETA of when you will have it ready, thanks!

**Comment by pogwon** [comment]
Iteration 2:

- Changed colors of the zoom buttons for better accessibility
- Explored a popover feature that explicitly describes disabled status and how to enable zooming
- Exploring a change in the cursor to indicate a disabled status

<img width="1596" alt="Screenshot 2024-06-14 at 4 43 34 PM" src="https://github.com/hackforla/311-data/assets/129242704/0c6fba8b-0b21-4985-99fd-8798286e2dae">

**Comment by pogwon** [comment]
@ryanfchase 
For one of the designs for Iteration 2, we are exploring a change in cursor state to indicate that the zoom feature is disabled. Is this a realistic solution that the dev team can implement?

<img width="1414" alt="Screenshot 2024-06-14 at 4 52 17 PM" src="https://github.com/hackforla/311-data/assets/129242704/f173de83-2b2d-48d2-8468-543414c01141">

**Comment by ryanfchase** [comment]
> @ryanfchase For one of the designs for Iteration 2, we are exploring a change in cursor state to indicate that the zoom feature is disabled. Is this a realistic solution that the dev team can implement?

@pogwon I think so, so long as we are provided the entire cursor (the pointer _and_ the crossed out circle) as a single SVG or similar asset.
- Example in a [sandbox](https://codesandbox.io/p/sandbox/keen-snow-im111) from this [SO post](https://stackoverflow.com/questions/66840945/specifying-custom-cursor-in-react)
- I'm going to ask for comment in our slack channel to confirm

**Comment by ryanfchase** [comment]
Adding labels and modifying board status while we wait for input @pogwon .I shall put everything back when this is addressed 😄

**Comment by aqandrew** [comment]
@pogwon I think the change in cursor state you're looking for is the CSS rule `cursor: not-allowed` ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)):

https://github.com/hackforla/311-data/assets/9038965/f83360b2-04f1-400d-b6d1-6c05f4a015d8

This is a native/cross-platform solution that is a lot less work than replacing the cursor with an image asset.

I'm guessing that we would add these controls with Mapbox's [NavigationControl](https://docs.mapbox.com/mapbox-gl-js/example/navigation/). If that control doesn't give us the option to limit zoom + set the not-allowed cursor out of the box, then we can style the cursor with CSS based on mouseover events: https://github.com/mapbox/mapbox-gl-js/issues/1353#issuecomment-406748057

**Comment by ryanfchase** [comment]
@pogwon following up on @aqandrew's comment, I think we can move forward with `cursor: not-allowed` cursor state for this deliverable.

**Comment by pogwon** [comment]
@ryanfchase Sounds good - thanks! Going to ask for feedback from the design team one more time at this week's meeting before deciding on the final design for handoff.

**Comment by pogwon** [comment]
ETA for Completion: Wednesday June 26, 2024.

**Comment by ryanfchase** [comment]
@pogwon I've moved this to `In Progress` since you've provided an ETA -- thanks!

**Comment by pogwon** [comment]
Final designs with notes [Link to Figma File](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13065-9261&t=cblYs0QCW8oQn2h8-1)

**Comment by pogwon** [comment]
Final designs with notes [Link to Figma File](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13065-9261&t=cblYs0QCW8oQn2h8-1)

<img width="857" alt="Screenshot 2024-06-26 at 7 46 40 PM" src="https://github.com/hackforla/311-data/assets/129242704/985ed429-4c5c-4e2b-9c79-840dfdc58242">

**Comment by pogwon** [comment]
This ticket is ready for engineering hand off. @ryanfchase

**Comment by ryanfchase** [comment]
Thank you @pogwon -- I'll get this converted to a dev ticket.
- ETA 6/30
- availability: 10-3p over the weekend

**Comment by ryanfchase** [comment]
@pogwon @annaseulgi Happy 1st day of July break! I mean to do this before break started, please review at your convenience. I'll add it to the 1st agenda of August so we don't forget.

In the PM Suggested Changes in the main issue, we noted the following...

> [User] can't scroll out too far or scroll away too far while an NC is selected.

I also think that we should be establishing a minimum zoom level. Currently, regardless of NC selection, a user is allowed to scroll too far (e.g. a street corner will take up the entire screen) as well as zoom out too far (we can view the entire Earth as a globe in space).

### Action Items

In order for me to fully consider this ticket closed, Designer will help confirm the following:

- [ ] Zoom controls when an NC is bound to the following...
  - [ ] Minimum zoom will frame the NC (e.g. the default zoom level when selecting an NC)
  - [ ] Maximum zoom will be the Site maximum zoom (see below)
- [ ] Site minimum zoom level will be at the "street-block level" (e.g. at most we can zoom in on a particular block)
- [ ] Site maximum zoom level will be the base zoom level that is present when the map is loaded

**Comment by ryanfchase** [comment]
### TODO for dev lead
- [ ] look at mapbox docs
  - [ ] review zoom levels and convey them to design team (share links to the necessary docs)
  - [ ] see if there are any more relevant docs
- [ ] maybe review material UI and make sure design and dev are on the same page

**Comment by ryanfchase** [comment]
@pogwon @Joy-Truex I'm still working on providing the Mapbox docs that will allow us to convey zoom levels and other map-styling info between design and dev team.

I did have a question about the location of the zoom controls. Typically the Privacy Policy modal takes up the bottom left corner of the screen on site-open. I notice that this is also the desired location of the zoom controls, as designed by @pogwon. While not perfect, I think this is fine -- but I just wanted to run it by you both in case you felt strongly about addressing this. I believe Bonnie says we should be encouraging users to deal with the Privacy Policy modal immediately, rather than let it remain open for the entirety of their session.

**Comment by ryanfchase** [comment]
@Joy-Truex @allisonjeon 

I've been reviewing the Mapbox docs, and I just want to share a few highlights:
- the Mapbox website hosts a [Glossary ](https://docs.mapbox.com/help/glossary/)of map rendering terms (e.g. [zoom level](https://docs.mapbox.com/help/glossary/zoom-level/), [zoom extent](https://docs.mapbox.com/help/glossary/zoom-extent/), [tile pack](https://docs.mapbox.com/help/glossary/tile-pack/), etc). As leads, I recommend bookmarking this page for reference in the future
- As far as zoom level, the [Zoom Level glossary page](https://docs.mapbox.com/help/glossary/zoom-level/) on this is most useful. These are the two zoom levels I believe we should use:
  - max zoom (most granular): 18, which is a few higher than the "Buildings" visibility
  - min zoom (most zoomed out): 9, which is one less than the "Large roads" visibility
- as far as "framing the NC when selected", I believe these behaviors are useful:
  - prevent user from zooming out beyond framed NC (e.g. zoom out button is disabled)
  - prevent user from panning the map beyond the framed NC (note: I actually don't think there is any useful UI feedback for this, input welcome).

### Resources

Some links I used to compile these notes:
- dev example of setting zoom levels: https://docs.mapbox.com/mapbox-gl-js/example/navigation/
- dev example of limiting pan area: https://docs.mapbox.com/mapbox-gl-js/example/restrict-bounds/
- some example code I used in a codebox:

<details><summary>Mapbox JS for setting max/min zoom level</summary>
<p>

```js

mapboxgl.accessToken = 'pk.eyJ1IjoicnlhbmNoYXNlIiwiYSI6ImNsN2pvbG8wMTAwOHczeHFuYWNqbDJhaG4ifQ.BEyTQiMJSHPJX7uHLAGzCg';
    const map = new mapboxgl.Map({
        container: 'map', // container ID
        // Choose from Mapbox's core styles, or make your own style with Mapbox Studio
        style: 'mapbox://styles/mapbox/streets-v12', // style URL
        // center: [-74.5, 40], // starting position
        center: [-118, 34],
        zoom: 9, // starting zoom,
        maxZoom: 15,
        minZoom: 9
    });

    // Add zoom and rotation controls to the map.
    map.addControl(new mapboxgl.NavigationControl());

```

</p>
</details>

**Comment by pogwon** [comment]
> @pogwon @Joy-Truex I'm still working on providing the Mapbox docs that will allow us to convey zoom levels and other map-styling info between design and dev team.
> 
> I did have a question about the location of the zoom controls. Typically the Privacy Policy modal takes up the bottom left corner of the screen on site-open. I notice that this is also the desired location of the zoom controls, as designed by @pogwon. While not perfect, I think this is fine -- but I just wanted to run it by you both in case you felt strongly about addressing this. I believe Bonnie says we should be encouraging users to deal with the Privacy Policy modal immediately, rather than let it remain open for the entirety of their session.

@ryanfchase Thanks for letting me know - I'm personally leaning towards keeping it as is, since you mentioned Bonnie's thoughts about dealing with the privacy policy modal. But I'll ask the design team this week what they think about "locking" a control behind the modal and provide updates.

**Comment by ryanfchase** [comment]
Just wanted to share the conversation from Wednesday (8/28/2024). It sounds like we are moving forward with leaving the navigation controls in the bottom left corner as per the spec. We are fine with it being obscured by the Privacy Policy modal since it will be dismissed by the user.

I still think I want to review the mapbox documentation and styling capabilities with dev + design teams (I have outlined above). We can make time for that at an upcoming meeting.

**Comment by ryanfchase** [comment]
@Joy-Truex @pogwon I actually think we can nearly sign off on this ticket -- I do have one feedback request. In the final frame on @pogwon's hand off screenshot, the pop-up says:

```
Zoom features are disabled while locked into a neighborhood council.

To enable zoom features, please exit by clicking out of the selected area.
```

Requested Changes
- I actually do not want to completely limit zoom controls. I think we should simply limit zooming-out (which may require an alteration of the design to only disable half the zoom control)

Any thoughts on removing the pop-up text completely? Especially if we are planning on a "reset all" button in the search & filters modal? I'll add this to our upcoming Wednesday agenda to ensure there is time to discuss this.

**Comment by pogwon** [comment]
Sorry, I was out sick for last week's meeting. I don't have a problem with removing the pop-up text completely. But a potential issue that may arise is displaying only one available option within our current designs could be confusing for users (SS shows how it would look if Zoom in is available but Zoom out is disabled)

<img width="134" alt="Screenshot 2024-09-18 at 6 21 57 PM" src="https://github.com/user-attachments/assets/7bf26602-af76-4970-8448-e906141a2648">

This probably won't be an issue if users mainly use the scroll wheel or pinching to zoom but it could be confusing if they rely on the zoom buttons. There are some new potential button designs I am considering that I can have ready by the end of this week (Friday, September 20) that may look clearer when only one option is enabled.

**Comment by pogwon** [comment]
Here are two potential updated designs for the zoom buttons, along with disabled states (for zoom-in and out):

<img width="513" alt="Screenshot 2024-09-20 at 4 13 19 PM" src="https://github.com/user-attachments/assets/976264dc-429c-4cb8-86d9-2c31f149b266">

I am leaning towards the above design as it is more consistent with other maps' designs (Google, Yelp, Airbnb, etc.) but will also ask for feedback in our UI/UX Slack channel.

**Comment by ryanfchase** [comment]
@pogwon thank you! Yeah I think upper design is what I'm leaning towards as well. I think it's easier to distinguish the disabled state. But interested to hear what the others think.

**Comment by pogwon** [comment]
Looking at feedback, the general consensus was that the top (lighter) design would fit better. There was one suggestion that maybe it can switch back and forth depending on if the map changes from dark to light. I'm not sure if this can be implemented but I think we can discuss it at this week's meeting and make a final decision to move forward.

**Comment by pogwon** [comment]
After some research into other map behaviors, there are very few examples where zoom buttons change as the map color changes. I think it would be best to move forward with just the lighter designs. I can prepare those for handoff along with different states (disabled, active, hover) and link the Figma file here.

@ryanfchase Should the zoom levels we reviewed from the MapBox docs be included in there as well?

**Comment by ryanfchase** [comment]
> After some research into other map behaviors, there are very few examples where zoom buttons change as the map color changes. I think it would be best to move forward with just the lighter designs. I can prepare those for handoff along with different states (disabled, active, hover) and link the Figma file here.
> 
> @ryanfchase Should the zoom levels we reviewed from the MapBox docs be included in there as well?

Let's just focus on the lighter design, the different states, and any on-hover info boxes that pop up. I have been able to communicate the zoom levels to the devs -- unless you're comfortable identifying and demonstrating zoom levels with the map. 

Otherwise, we can stick to communicating it as the following:
- Max zoom when NC is selected
- Min zoom when NC is selected
- Min zoom when no NC is selected
- (there is no max zoom when no NC is selected... I don't see a need for this, but open to discussion)

If anything is still unclear, please reach out on Slack and we can come to an agreement.

cc @DrAcula27

**Comment by pogwon** [comment]
After designing the hover states, there are a few different options. I just want to get some feedback from the design team at tonight's meeting and will post/submit final designs for handoff afterwards.

**Comment by pogwon** [comment]
Finalized zoom icons are in the [handoff section of the Figma file](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=14236-4123&t=QskwB6553gRAY1WR-4). As noted, hover states only apply when zoom function is enabled.


<img width="909" alt="Screenshot 2024-10-15 at 5 24 37 PM" src="https://github.com/user-attachments/assets/d9ca78ce-bd7c-4e96-bbf8-0670b99b058f">

**Comment by ryanfchase** [comment]
Hi @Joy-Truex @allisonjeon, has this work been reviewed and approved? Please leave a comment if so, PMs will have a brief look before officially handing this off to dev.

**Comment by Joy-Truex** [comment]
> Hi [@Joy-Truex](https://github.com/Joy-Truex) [@allisonjeon](https://github.com/allisonjeon), has this work been reviewed and approved? Please leave a comment if so, PMs will have a brief look before officially handing this off to dev.

Reviewed and approved. TY!!

**Comment by DrAcula27** [comment]
### Closing Issue
Fixed by:
PR #1860
