### ISSUE TITLE
Spike: Data Loading Checklist for Engineers to document loading times under various conditions 

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1716]
### Overview
We need a checklist for engineers to document loading times under various conditions so that we can improve load times, upload alerts about load times or create load time fillers to enhance user experience, minimize confusion. 

### Action Items
measure and document load times based on selection 
measure and document load times based on condition
offer suggestions to update/ improve loading time
Identify various conditions that can impact data loading performance (e.g., network latency, server load, data volume
provide recommendations for optimizing data loading performance based on test findings
Provide recommendations to optimize wait experience
Document any changes made to the system or environment

measure load times: selection based:
(- long timeframe with few request types, - short timeframe with more/all request types)
Request status "Open" (default)
- [ ] choose 3 months, 3 request types
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
- [ ] choose 1 week with 2 request types
Request status "All"
- [ ] choose 3 months, 3 request types
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
- [ ] choose 1 week with 2 request types

measure load times: condition based 
- [ ] using local machine
- [ ] using https://hackforla.github.io/311-data

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
https://hackforla.github.io/311-data

**Comment by ryanfchase** [comment]
Thanks @cottonchristopher -- now going to meet with @Skydodle and consider next steps for making this available for devs to pick up.

**Comment by ryanfchase** [comment]
- ETA: 6/23/24 @ 6pm PT
- available till evening

**Comment by ryanfchase** [comment]
### Load Time Criteria

- Platform: Local
- Request Status: Open

### Results

- [ ] choose 3 months, 3 request types
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
- [ ] choose 1 week with 2 request types

**Comment by ryanfchase** [comment]
measure load times: 
- Hosted
- Request Status: All

- [ ] choose 3 months, 3 request types
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
- [ ] choose 1 week with 2 request types

**Comment by ryanfchase** [comment]
### Load Time Criteria
- Platform: Hosted
- Request Status: All

### Results
- [ ] choose 3 months, 3 request types
  - Dataset registration & table creation (by year) time: 32 ms.
  - Data loading time: 1576 ms
  - Map loading time: 12832 ms
  - Pin load time: 78614 ms
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
  - Dataset registration & table creation (by year) time: 14858 ms.
  - Data loading time: 381 ms
  - Map loading time: 3046 ms
  - Pin load time: 39322 ms
- [ ] choose 1 week with 2 request types

**Comment by ryanfchase** [comment]
### Load Time Criteria
- Platform: Hosted
- Request Status: Closed

### Results
- [ ] choose 3 months, 3 request types
  - Dataset registration & table creation (by year) time: 25 ms.
  - Data loading time: 1461 ms
  - Map loading time: 9291 ms
  - Pin load time: 53692 ms
- [ ] choose 3 months, 1 request type  
- [ ] choose 1 week, chose all requests
- Dataset registration & table creation (by year) time: 108 ms.
- [ ] choose 1 week with 2 request types

### Notes
- since we load data by default, it is impossible to get a first-time load on Closed requests, since Closed is just a filter on the total number of requests

**Comment by ryanfchase** [comment]
- [ ] Add to agenda

Question for @efrenmarin45 
- Wondering if this ticket will be useful for you since you are assessing performance for pins and state management

**Comment by efrenmarin45** [comment]
These load times are in correlation with issue #1865. 
Notated conditions with the current build as a control and the modified version not using the pin Sagas as the variable.

| Load Time Criteria | |
|---------------------|-|
| Platform | local |
| Request Status | Open |
| Commit Hash | -- |
| Operating System | Windows |
| Browser | Firefox |

| Data Filters | Dataset Registration & Table Creation (by year) Time<br> (in milliseconds) | Data Loading Time (in milliseconds) | Map Loading Time (in milliseconds) | &nbsp;Pin Loading Time (in milliseconds)&nbsp; |
|--|--|--|--|--|
| 3 Months, 3 Request Types | **With Saga:** 28876 ms<br>**W/O Saga:** 28945 ms | **With Saga:** 3999 ms<br>**W/O Saga:** 3975 ms | **With Saga:** 8360 ms<br>**W/O Saga:** 8604 ms | **With Saga:** 55154 ms<br>**W/O Saga:** 54449 ms |
| 3 Months, 1 Request Type |**With Saga:** 28485 ms<br>**W/O Saga:** 28529 ms | **With Saga:** 4014 ms<br>**W/O Saga:** 3975 ms | **With Saga:** 8610 ms<br>**W/O Saga:** 8504 ms | **With Saga:** 55040 ms<br>**W/O Saga:** 54971 ms |
| 1 Week, All Requests Types |**With Saga:** 28242 ms<br>**W/O Saga:** 28322 ms | **With Saga:** 308 ms<br>**W/O Saga:** 309 ms | **With Saga:** 545 ms<br>**W/O Saga:** 551 ms | **With Saga:** 29948 ms<br>**W/O Saga:** 30070 ms |
| 1 Week, 2 Request Types |**With Saga:** 28207 ms<br>**W/O Saga:** 28777 ms | **With Saga:** 307 ms<br>**W/O Saga:** 320 ms | **With Saga:** 556 ms<br>**W/O Saga:** 548 ms | **With Saga:** 30251 ms<br>**W/O Saga:** 30517 ms |
