### ISSUE TITLE
Add comments with card information into 311-Data Wiki after migration

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1755]
### Overview

We need to copy all of the comments from the migration ticket into the wiki so that we can conclude the migration process

### Action Items

Step One - Configure the Wiki

- [x] Determine which section of the [Wiki ](https://github.com/hackforla/311-data/wiki)that the below should go
  - [ ] Consider making a page with the new info
  - [x] Consider making a section for each card on the Home page (+1 from RC)

Step Two - Move the cards over (mark progress here _and_ at linked card)

- [x] [Meeting Times](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155425149)
- [x] [Issues by role](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155426944)
- [x] [Handy Links](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155428184)
- [x] [Recruiting & Onboarding](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155428802)
- [x] [Check for missing labels](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155429640)
- [x] Questions column in new project board needs [this description](https://github.com/hackforla/311-data/issues/1751#issuecomment-2155431839)

### Resources

Note from Ryan

- Wiki is composed of a main Home page, and then several linked sub-pages
  - The homepage gets a Table of Contents for content on the homepage, and then dropdowns with sub-pages (which you can expand to see sections within those pages)
  - each sub-page allows you to edit the sidebar, the home page cannot edit it's table of contents
- Each page is just pure markdown, and new pages are automatically created under the homepage, e.g. there is no real page management interface

Useful Links
- Migration Ticket: https://github.com/hackforla/311-data/issues/1751
- New project board: https://github.com/orgs/hackforla/projects/63/views/1
- Team Wiki: https://github.com/hackforla/311-data/wiki

**Comment by bberhane** [comment]
ETA: 6/12 by 6:45pm PT

**Comment by ryanfchase** [comment]
That's odd, let's review this as part of tonight's [agenda](https://github.com/hackforla/311-data/issues/1546#issuecomment-2166926851)

**Comment by bberhane** [comment]
ETA 6/15 by 7pm

**Comment by bberhane** [comment]
Wiki and project board updated
