### ISSUE TITLE
Milestone: Review and Update 

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1764]
### Overview
We need to review and update milestones as we near launch and have made updates to ensure that the milestones are getting us closer to milestones are managed in such a way that will facilitate our progress to launch and direction post launch

### Action Items

- [x] Update milestone Excel sheet 
- [x] Review Milestones to ensure that they are appropriately numbered
- [x] Review milestones to ensure that they are appropriately described
- [x] Review milestones that are in question (up-for-debate) 
- [x] Update Milestones

### Resources/Instructions
Milestones Excel: (https://docs.google.com/spreadsheets/d/1Agx-b6XkmJHZU14eu7JZIAtrGWKlJUWs2iQO0IUCotU/edit?gid=0#gid=0)
Milestones (as housed in github): https://github.com/hackforla/311-data/milestones

**Comment by ryanfchase** [comment]
I've added a feature and a size, and I think it's good to move to Prioritized Backlog!

**Comment by cottonchristopher** [comment]
@bberhane and @ryanfchase Attached is the Updated Milestone spreadsheet:    https://docs.google.com/spreadsheets/d/1Agx-b6XkmJHZU14eu7JZIAtrGWKlJUWs2iQO0IUCotU/edit?gid=0#gid=0    
I added some items to review in red. 
We can either add to the PM agenda for when we meet or review separately. Whichever seems more appropriate.

**Comment by bberhane** [comment]
Let's look together during our PM meeting. Will add to the agenda!

**Comment by bberhane** [comment]
Approved
