### ISSUE TITLE
Epic: Testing and Code Coverage

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1768]
### Overview

We need to implement a frontend testing framework for our project so we can prevent bugs and regressions, as well as provide a means of teaching other volunteers how to utilize testing to improve their code

### Action Items

- [ ] https://github.com/hackforla/311-data/issues/1334
- [ ] create a ticket template for unit and integration tests
  - [ ] and create a unit test as an example
  - [ ] create an integration test as an example
- [ ] create tickets for each documented user flow in Figma
- [ ] create wiki page for testing
  - [ ] include some basic definitions for testing terminology
  - [ ] list our testing tools
  - [ ] how to utilize unit/integration test template

**Comment by ryanfchase** [comment]
Updated to include:
- [ ] https://github.com/hackforla/311-data/issues/1824
- [ ] https://github.com/hackforla/311-data/issues/1823
