### ISSUE TITLE
Epic: Documentation and Wiki

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1796]
### Overview

We need to track our review of the Wiki, adding entries and modifying deprecated pages to better reflect the current frontend-only architecture.

### Action Items

Review the following featured pages...
- [ ] Home
- [ ] Join Us
- [ ] Deliverables
- [ ] Prototype Proposals
- [ ] Resources

Additional Pages to review...
(TODO: organize these into logical sub-groups)

- [ ] [20200305 UX Interview w Thomas D](https://github.com/hackforla/311-data/wiki/20200305-UX-Interview-w-Thomas-D)
- [ ] [20200414 NC Workshop Meeting Minutes](https://github.com/hackforla/311-data/wiki/20200414-NC-Workshop-Meeting-Minutes)
- [ ] [20200810 UX Interview (Elida Mendez)](https://github.com/hackforla/311-data/wiki/20200810-UX-Interview-(Elida-Mendez))
- [ ] [2023 Data Server Not Functioning PostMortem](https://github.com/hackforla/311-data/wiki/2023-Data-Server-Not-Functioning-PostMortem)
- [ ] [August 2019 Agenda](https://github.com/hackforla/311-data/wiki/August-2019-Agenda)
- [ ] [Creating an Issue Template](https://github.com/hackforla/311-data/wiki/Creating-an-Issue-Template)
- [ ] [Data Science Recruiting](https://github.com/hackforla/311-data/wiki/Data-Science-Recruiting)
- [ ] [Deliverables](https://github.com/hackforla/311-data/wiki/Deliverables)
- [ ] [Diff Dashboard](https://github.com/hackforla/311-data/wiki/Deliverables)
- [ ] [Existing Tools](https://github.com/hackforla/311-data/wiki/Existing-Tools)
- [ ] [How to Communicate with the Team](https://github.com/hackforla/311-data/wiki/How-to-Communicate-with-the-Team)
- [ ] [How to Create Issues](https://github.com/hackforla/311-data/wiki/How-to-Create-Issues)
- [ ] [How to Join the Engineering Team](https://github.com/hackforla/311-data/wiki/How-to-Join-the-Engineering-Team)
- [ ] [How to Read and Interpret Labels](https://github.com/hackforla/311-data/wiki/How-to-Read-and-Interpret-Labels)
- [ ] [How to Write a UX Research Issue](https://github.com/hackforla/311-data/wiki/How-to-Write-a-UX-Research-Issue)
- [ ] [How to Write an Issue for a Data Scientist](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-a-Data-Scientist)
- [ ] [How to Write an Issue for a UI UX Designer](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-a-UI-UX-Designer)
- [ ] [How to Write an Issue for an Engineer](https://github.com/hackforla/311-data/wiki/How-to-Write-an-Issue-for-an-Engineer)
- [ ] [How to Write Issues for Product Managers](https://github.com/hackforla/311-data/wiki/How-to-Write-Issues-for-Product-Managers)
- [ ] [Initiative ROI](https://github.com/hackforla/311-data/wiki/Initiative-ROI)
- [ ] [Introduction to Our Product](https://github.com/hackforla/311-data/wiki/Introduction-to-Our-Product)
- [ ] [Introduction to Our Users](https://github.com/hackforla/311-data/wiki/Introduction-to-Our-Users)
- [ ] [Joining the 311 Team](https://github.com/hackforla/311-data/wiki/Joining-the-311-Team)
- [ ] [Joining the Data Science Team](https://github.com/hackforla/311-data/wiki/Joining-the-Data-Science-Team)
- [ ] [Joining the Product Management Team](https://github.com/hackforla/311-data/wiki/Joining-the-Product-Management-Team)
- [ ] [Joining the UI UX Research Team](https://github.com/hackforla/311-data/wiki/Joining-the-UI-UX-Research-Team)
- [ ] [Joining the UI UX Team at 311 Data](https://github.com/hackforla/311-data/wiki/Joining-the-UI-UX-Team-at-311-Data)
- [ ] [July 2019 Agenda](https://github.com/hackforla/311-data/wiki/July-2019-Agenda)
- [ ] [March 2020 311 MVP Alpha UX Interview Notes](https://github.com/hackforla/311-data/wiki/March-2020---311-MVP-Alpha-UX-Interview-Notes)
- [ ] [Onboarding New Team Members](https://github.com/hackforla/311-data/wiki/Onboarding-New-Team-Members)
- [ ] [Positions We Need](https://github.com/hackforla/311-data/wiki/Positions-We-Need)
- [ ] [RequestStatus](https://github.com/hackforla/311-data/wiki/RequestStatus)
- [ ] [September 2019 Agenda](https://github.com/hackforla/311-data/wiki/September-2019-Agenda)
- [ ] [Software Development Engineer Test](https://github.com/hackforla/311-data/wiki/Software-Development-Engineer-Test)
- [ ] [Storing Data in the Repository for a "Frontend Only" Web App](https://github.com/hackforla/311-data/wiki/Storing-Data-in-the-Repository-for-a-%22Frontend-Only%22-Web-App)
- [ ] [Team](https://github.com/hackforla/311-data/wiki/Team)
- [ ] [Team Photos](https://github.com/hackforla/311-data/wiki/Team-Photos)
- [ ] [Training for User Interviews](https://github.com/hackforla/311-data/wiki/Training-for-User-Interviews)
- [ ] [UI UX (Product) Designer 311 Data, Hack For LA](https://github.com/hackforla/311-data/wiki/UI-UX-(Product)-Designer---311-Data,-Hack-For-LA)
- [ ] [Visualization Exploration](https://github.com/hackforla/311-data/wiki/Visualization-Exploration)

### Resources/Instructions

Quick links
- [Wiki](https://github.com/hackforla/311-data/wiki)

**Comment by ExperimentsInHonesty** [comment]
Tracy wants us to look at [311-Data: Project Documentation #1863](https://github.com/hackforla/311-data/issues/1863) as it relates to section C5 -C9

Recorded to the cloud Tracys KT comments on 2025-02-15 11:48 - 11:53 zoom 1
