### ISSUE TITLE
Decision Record: Upgrading to Vite from Webpack

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1829]
### Overview
We need create a Decision Record for incorporating the Vite build system so that volunteers know why we moved away from Webpack and what benefits were gained from Vite

### Action Items

- [ ] Create decision records page in Solutions Adopted for Vite migration from Webpack
- [x] Using template in wiki page `Decision Reocrds on Solutions Adopted`, create a new page: "DR: Upgrade to Vite from Webpack"
  - [x] add description of the Webpack build tool
  - [x] add description of the Vite build tool
  - [x] summarize case for Vite outlined in migration ticket: https://github.com/hackforla/311-data/issues/1778
  - [x] note performance boost we get from switching to vite: https://github.com/hackforla/311-data/issues/1778#issuecomment-2290247245
  - [x] make a section called Common Vite Migration Problems:
    - [x] note down what happens when you fail to specify `base` property in `vite.config.js`: https://github.com/hackforla/311-data/issues/1778#issuecomment-2430329390
- [ ] Add a link to this new page onto the main Decision Record page's listing
- [ ] Add a link to this new page onto the Decision Records Adopted page's listing

### Resources/Instructions

311 Data Decision Record Examples
- [Decision Records on Solutions Adopted](https://github.com/hackforla/311-data/wiki/Decision-Records-on-Solutions-Adopted)
- [Decision Records on Solutions Not Implemented](https://github.com/hackforla/311-data/wiki/Decision-Records-on-Solutions-Not-Implemented)
  - Example: [DR: Implement Prettier Configurations to standardize code formatting](https://github.com/hackforla/311-data/wiki/DR:-Implement-Prettier-configurations-to-standardize-code-formatting)

Build Tool: Basic Info
- [Webpack: Introduction](https://webpack.js.org/api/)
- [Vite: Getting Started](https://vite.dev/guide/)

**Comment by ryanfchase** [comment]
This ticket is ready to be picked up 👍

**Comment by kdow** [comment]
ETA: 3/26/25
Availability: Mon-Fri 1pm - 4pm

**Comment by ryanfchase** [comment]
Hi @kdow,

Per org requirements, we are pausing all work on 311 Data tickets from April to May 2025. There must not be any tickets in-progress by 2025-04-01. Please help us prepare by proceeding with one of the following options:
- if you are on-track to complete this ticket by 2025-03-31, please continue your work and prepare to move the ticket to In-Review by that date
- if you do not believe this ticket can be completed by 2025-03-31, please prepare this ticket to be moved back to Prioritized Backlog
  - You must be prepared to provide a partial-work hand off. Please leave a comment with the following information:
    - Your latest progress up to date
    - A link to a published branch with your code changes, ensure your code is well-documented with comments in the case somebody else resumes your work. If your work is not suitable for a branch, please create a folder in the engineering shared drive (give it the same title as this ticket, be sure to include the ticket number). In this folder, create any resources you need to hand off your work.
  - Conclude your work by moving this ticket back to the Prioritized Backlog

Thank you for your help. If you have questions concerning handing off your ticket, please leave your question in a comment. If you have questions regarding your schedule from April to May, please leave your question as a reply to the work pause announcement in slack.

### Resources
- Link to work pause announcement: https://hackforla.slack.com/archives/CJY4R382X/p1742933062574999
- Link to the 311 Data Engineering Drive: https://drive.google.com/drive/u/0/folders/1DvIrgxBIbb6KnN_mmAAUi4OIuCUdrqQ-

**Comment by kdow** [comment]
I'm on track to complete before April. I'll be posting my draft and moving the ticket to In Review this Friday and can make any changes if needed before Tuesday.

**Comment by kdow** [comment]
Here is my draft: https://github.com/hackforla/311-data/wiki/DR:-Upgrade-to-Vite-from-webpack

I'll add the link to the DR listing pages once it's been reviewed.

**Comment by ryanfchase** [comment]
@kdow I'm approving this work, thank you for putting it together!

For posterity, I'm copy-pasting the contents into a comment here in case that URL changes, or the content gets modified in the future:

---

<details><summary>DR: Upgrade to Vite from Webpack</summary>
<p>

This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/311-data/wiki/Decision-Records-on-Solutions-Adopted).

### Issue 
[#1778](https://github.com/hackforla/311-data/issues/1778)

### Problem Statement
We wanted to set up a front-end testing framework. Our team ran into issues configuring Jest with webpack, the existing build tool. While exploring alternatives, another issue with webpack was highlighted: the slow refresh times were a pain point for developers.

[Webpack](https://webpack.js.org/) is used to compile JavaScript modules with dependencies into static assets. The entire page must be refreshed, which triggers a request for data every time a JS module is changed. i.e., whenever a JS/JSX file is saved.

### Potential Solution

Vite is an alternative build tool that could be simpler for setting up testing using Vitest. Additionally, Vite's HMR (hot module reloading) could improve the developer experience by updating the dev server almost instantly when saving changes to files during development. 

[Vite](https://vite.dev/) is an open-source frontend build tool that aims to provide a faster and leaner development experience for modern web projects. Vite provides an [HMR API](https://vite.dev/guide/api-hmr.html) over native [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). Frameworks with HMR capabilities can leverage the API to provide instant, precise updates without reloading the page or removing application state.

### Feasibility Determination

[Testing](https://github.com/hackforla/311-data/issues/1778#issuecomment-2290247245) determined that Vite could be successfully set up and run on GitHub Pages. 

HMR showed a huge performance increase. An update using webpack averaged 7.88 seconds, while Vite took 0.58 seconds, 13.59 times faster than webpack's refresh time.

Basic front-end tests were [successfully implemented](https://github.com/hackforla/311-data/pull/1873) using Vitest.

#### Common Vite Migration Problems

**Problem**: Page not loading and Network tab showing assets returning 404.

**Solution**: Add/update the `base` [config option](https://vite.dev/config/shared-options.html#base) in `vite.config.js` to match the name of your repository. This will configure Vite's build so that bundled assets are requested from `https://{username}.github.io/{repo name}/assets/`.


</p>
</details> 

---

Nice work!
