### ISSUE TITLE
Migrate devs to Vite - checklist

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1834]
### Overview
We need to track each dev that is currently active and ensure that they have migrated to Vite in order to avoid merge conflicts or other issues.

### Action Items

Create comments for each dev, use template to track their progress
- [ ] Tracy
- [ ] Ryan C
- [ ] Shannan
- [ ] Billy Phan
- [ ] Danielle
- [ ] Kelly
- [ ] Brandon
- [ ] Dorian
- [ ] Mrudula
- [ ] Sophia

#### Instructions for Vite Environment Variables

All environment variables must have a prefix of VITE. Two tokens are most relevant for your dev environment:
- `MAPBOX_TOKEN` becomes `VITE_MAPBOX_TOKEN`
- `CONTENTFUL_SPACE` becomes `VITE_CONTENTFUL_SPACE`

#### Action Item Templates For Devs

Mandatory for each dev, everyone's tracking comment includes these steps.

```
## Name
- github id: 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`
```

#### Optional Steps for Dev

Only follow these steps if you need to be able to publish your fork via gh pages.
```
### Action Items: GH Pages from Fork

- [ ] Fork the project once the `1778-migrate-from-webpack-to-vite` branch has been merged into `main`
- [ ] Modify `vite.config.js`:
  - [ ] add an attribute called `base`, where value is the name of your fork
  - e.g. `{ ..., base: 'my-311-data', ... }`, where the name of your fork is `my-311-data`
- [ ] For each of the variables in your `.env`...
  - [ ] go to the Action Secrets page in your forked repo's settings
    - e.g. Settings > Secrets & Variables > Actions
  - [ ] create a Repository Secret, matching the key and value of the `.env` variables
```

**Comment by ryanfchase** [comment]
## Tracy
- github id: @traycn 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] rename all variables in your `.env` with VITE prefix
- [ ] `npm run setup`
  - this should tell you if you failed to migrate any tokens
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Ryan
- github id: @ryanfchase  

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Shannan
- github id: @funbunch 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Billy
- github id: @bphan002 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Danielle
- github id: @DrAcula27  

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Kelly
- github id: @kdow 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Brandon
- github id: @Brandoncyu 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Dorian
- github id: @DorianDeptuch 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Mrudula
- github id: @mru-hub 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by ryanfchase** [comment]
## Sophia
- github id: @sophia-bui 

### Scheduled Migration:
- 2024-10-30 7pm PT ( @ dev breakout room )

### Action Items
- [ ] `git checkout main`
- [ ] `git pull`
- [ ] `rm -rf node_modules`
- [ ] `npm install`
- [ ] `npm run setup`
- [ ] `npm start`
- [ ] Go to `http://localhost:5173/`

**Comment by aqandrew** [comment]
Hi @ryanfchase, what's the purpose of the Action Items: GH Pages from Fork checklist? I'm not clear on why each dev needs to deploy their own fork to GitHub Pages.

That second checklist seems like a lot of extra work, given that we can all continue to develop as normal (without forking) once #1822 has been merged into main.

**Comment by ryanfchase** [comment]
> Hi @ryanfchase, what's the purpose of the Action Items: GH Pages from Fork checklist? I'm not clear on why each dev needs to deploy their own fork to GitHub Pages.
> 
> That second checklist seems like a lot of extra work, given that we can all continue to develop as normal (without forking) once #1822 has been merged into main.

Hey @aqandrew -- it's not required. I figured I'd list the steps in case anyone else wanted to try it out. I've left it there so I can document it in a wiki page later. I'll update the ticket to note that it's optional. 😄

**Comment by bphan002** [comment]
> ## Billy
> * github id: @bphan002
> 
> ### Scheduled Migration:
> * 2024-10-30 7pm PT ( @ dev breakout room )
> 
> ### Action Items
> * [x]  `git checkout main`
> * [x]  `git pull`
> * [x]  `npm run setup`
> * [x]  `npm start`
> * [x]  Go to `http://localhost:5173/`

It's working for me.
