### ISSUE TITLE
WIP - Onboard & Offboard: UX Research

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1854]
### Dependency
The need to onboard/offboard a new person on to the UX Research team

### Overview
We need to have a checklist of items to do when a product manager onboard and offboards so that the process can be consistent and fast.

### Date Updated
Created: 10/30/2024

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Slack channel membership
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
   - [ ] Thursday PM meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
        - [ ] Change membership to maintainer
     - [ ] Add to read team
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #1546 and add them to role call and accountability check 
     - [ ] Assign them to the issue #1545 and add them to role call and accountability check 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] 311 Data Vault
       - [ ] Zoom vault
- [ ] Confirm that product member has access to Zoom Meeting Setup spreadsheet (if they are part of the product community of practice they will have access)
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ] 311-data@hackforla.org
- [ ] Sign up on [VRMS](vrms.io) so that they can add/adjust zoom calendar meetings
  - [ ] create a new profile
  - [ ] add yourself to the 311 Data project
  - [ ] Current Role: your real job
  - [ ] Desired Role: a role that you'd like to transition into through your work at Hack For LA
  - [ ] Add PM Admin Access on VRMS
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite
- [ ] Update the hackforla.org website team 


<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: PM, TPM, Project Manager, etc.
- Dashboard: L
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- Github
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="254">

</p>
</details> 

```
```
#### Offboard
- [ ] confirm that volunteer is not working on any guides in community of practice (if person does not respond to communication you can assume they are not active in the CoP)
- [ ] Remove from Google calendar invite
   - You need to log into the 311-data@hackforla.org account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the 311 Data project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Wednesday All-Team meeting (ad-hoc)
   - [ ] Thursday PM meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] 311 Data
       - [ ] Zoom vault
- [ ] Remove access from VRMS
   - ask admin if you don't have access
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] 311 Data (ie., project)  
      - [ ] demote to viewer
   - [ ] Product Management
      - [ ] demote to viewer
         - ask admin channel for support if you don't have access
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #1546,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #1545,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] 311-data@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki]
 - [ ] Update the hackforla.org website team 
 - [ ] Remove PM Admin Access on VRMS

```
Resources/Instructions
* [1password.com](https://1password.com/)
* [Google Drive Link](https://drive.google.com/drive/folders/0AK9EyXeY81U5Uk9PVA)
* [311 Data Team Roster](https://docs.google.com/spreadsheets/d/1OsLDl7Ciwj7WjtzbgDz38g4kpOMNlUhdjlgzQxtQTvM/edit?usp=drive_link)
* Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
* [GitHub Team URL](https://github.com/hackforla/internship)
    - [base (read)](https://github.com/orgs/hackforla/teams/311-data)
    - [write](https://github.com/orgs/hackforla/teams/311-data-write)
    - [maintain](https://github.com/orgs/hackforla/teams/311-data-maintain)
    - [triage] - does not exist
    - [admin](https://github.com/orgs/hackforla/teams/311-data-admin)
    - [other] - does not exist
* Shortcut for adding a profile to the desktop: chrome://settings/manageProfile
* WIKI: https://github.com/hackforla/311-data/wiki
* Figma [311 Data Figma](https://www.figma.com/files/team/1039983981189012111/311-data?fuid=604439038560392673)
* [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)
* [Zoom Meeting Setup spreadsheet](https://docs.google.com/spreadsheets/d/15P3MYyNQ7Xn0pqdrTynDDipjrLl5LCN9xHVLhk9SWa8/edit#gid=1276874845)
* [311-Data Issue tab](https://github.com/hackforla/311-data/issues)
* [311-Data Team Meeting Agenda](https://github.com/hackforla/311-data/issues/1545)
* [311-Data PM Meeting Agenda](https://github.com/hackforla/311-data/issues/1546)
- [Add/Remove PM Admin Access on VRMS](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=p-feature%3A+Add%2FRemove+PM+access%2C+role%3A+Product%2C+time-sensitive&projects=&template=add-remove-pm-admin-access.md&title=Add%2FRemove+PM+Admin+Access%3A+%5Bname+of+project%5D)
- [Project Profile Card review and update on hackforla.org website](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)

**Comment by ryanfchase** [comment]
#### Offboard Rong Ren

Confirm that volunteer's tickets are wrapped up
- [ ] for [all assigned tickets](https://github.com/hackforla/311-data/issues/assigned/rrhea22)
  - [ ] write comments leaving off any notes and resources, checking off all action items that were completed
  - [ ] leave a comment saying that this ticket was reviewed before offboarding
  - [ ] unassign
- [ ] for [all recently closed tickets](https://github.com/hackforla/311-data/issues?q=is%3Aclosed+is%3Aissue+assignee%3Arrhea22+)
  - [ ] ensure that team members have everything they need 
  - [ ] review all recently completed tickets

Organizational Bookkeeping
- [ ] Remove from Google calendar invite
   - You need to log into the 311-data@hackforla.org account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the 311 Data project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Wednesday All-Team meeting
- [ ] Google Drive
   - [ ] 311 Data (ie., project)  
      - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki]

**Comment by cottonchristopher** [comment]
#### Onboard Co-Lead Audreen Fune 
- [x] Slack channel membership
 - [x] Google Drive
   - [x] Add to drive as Manager
- [x] Add to Google calendar invites
   - [x] Wednesday All-Team meeting
   - [x] Product Planning meeting
   - [x] PM meeting
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [ x Check for Public
- [x] GitHub
     - [x] Add to write team
     - [x] Add to read team
     - [x] Confirm that their name is on their Github  
- [x] Figma
  - [x] invite
  - [ ] acceptance
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: UX Researcher
- Dashboard: M
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- Github
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="254">

</p>
</details>

**Comment by ryanfchase** [comment]
#### 2025-02-20 Onboard: Justyna
- [ ] Slack channel membership
 - [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Add to Google calendar invites
   - [ ] Wednesday All-Team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
     - [ ] Add to read team
     - [ ] Confirm that their name is on their Github  
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

<details><summary>Roster Required Fields</summary>
<p>


- Status: Active (required)
- Role: UX Researcher
- Dashboard: L
- email: required
- number/texting: optional
- Slack Name: required
- SlackID: required (click your slack picture > ellipses > copy member id)
- Github
- everything else: optional

<img src="https://github.com/hackforla/311-data/assets/6414668/45fc1596-ef3d-4aa5-a586-495e5eb1df58" width="128">

</p>
</details>

**Comment by ryanfchase** [comment]
#### Offboard Co-Lead: Audreen Fune
Confirm that volunteer's tickets are wrapped up
- [ ] for all assigned tickets
  - [ ] write comments leaving off any notes and resources, checking off all action items that were completed
  - [ ] leave a comment saying that this ticket was reviewed before offboarding
  - [ ] unassign
- [ ] for all recently closed tickets
  - [ ] ensure that team members have everything they need 
  - [ ] review all recently completed tickets

Organizational Bookkeeping
- [ ] Remove from Google calendar invite
   - You need to log into the 311-data@hackforla.org account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the 311 Data project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Wednesday All-Team meeting (ad-hoc)
- [ ] Google Drive
   - [ ] 311 Data (ie., project)  
      - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki]
 - [ ] Update the hackforla.org website team

**Comment by ryanfchase** [comment]
#### Offboard Brian Monroe
Confirm that volunteer's tickets are wrapped up
- [ ] for all assigned tickets
  - [ ] write comments leaving off any notes and resources, checking off all action items that were completed
  - [ ] leave a comment saying that this ticket was reviewed before offboarding
  - [ ] unassign
- [ ] for all recently closed tickets
  - [ ] ensure that team members have everything they need 
  - [ ] review all recently completed tickets

Organizational Bookkeeping
- [ ] Remove from Google calendar invite
   - You need to log into the 311-data@hackforla.org account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the 311 Data project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Wednesday All-Team meeting (ad-hoc)
- [ ] Google Drive
   - [ ] 311 Data (ie., project)  
      - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki]
 - [ ] Update the hackforla.org website team
