### ISSUE TITLE
311-Data Assessment for Pre- and Post-Launch

### ISSUE THREAD

**Issue by traycn** [hackforla/311-data#1862]
### Overview
We need to assess the remaining items for pre-launch and outline post-launch plans for the 311-data application.

### Action Items

- [ ] System Architecture Documentation:
  - [ ] Front-end: Mapbox integrations, Main react components, Utils, Userflow definition
  - [ ] Backend: Data source, dbProvider, What is: Data load into Mapbox integrations
  - [ ] DevOps: Developer CI, Testing, Deployment Branching strategies
  - [ ] Data: Data pipeline, Infrastructure for Analysis models
  - [ ] DevEx: Onboarding, Standardization (Linting, Formatting, Type Check), Branching strategy
- [ ] 311-Data Development: Quarterly Goals Documentation

- [ ] Pre-Launch:
  - [ ] Story of 311 (About Page)
    - [ ] [ insert existing ticket ]
  - [ ] Blank Map Feature: No data shown on map when first loaded (?optional)
    - [ ] [ insert existing ticket ]
  - [ ] Contact Form
    - [ ] [ insert existing ticket ]
  - [ ] Performance
    - [ ] Application doesn't crash (i.e.: this.[].param)
  - [ ] Implement Branching Strategy: Local Dev Branch, Staging, Production
    - [ ] Branching Strategy Documentation with Best Practices

- [ ] Post-Launch:
  - [ ] Filter/Search Re-design: Engineering Ticket
  - [ ] Service Request Modal Update: Engineering Ticket
  - [ ] Clean Param URL values
  - [ ] User Flow definition
  - [ ] Unit Testing, UI Testing 
    - [ ] __follow up conversation
  - [ ] QA Testing Process
    - [ ] __follow up conversation
  - [ ] Performance Benchmarking

**Comment by traycn** [comment]
Creating tickets to link to the action items from this initial Pre/Post-Launch Assessment.

**Comment by traycn** [comment]
Previous Persona's issue: https://github.com/hackforla/311-data/issues/1554

**Comment by ryanfchase** [comment]
Proposing new format for this ticket:

---


### Action Items

##### Roadmap and Planning
- [ ] https://github.com/hackforla/311-data/issues/1863
- [ ] https://github.com/hackforla/311-data/issues/1864

##### Pre-Launch:
- [ ] https://github.com/hackforla/311-data/issues/1756
- [ ] https://github.com/hackforla/311-data/issues/1623
- [ ] Map Accessibility
  - [ ] https://github.com/hackforla/311-data/issues/1870
- [ ] Performance
  - [ ] https://github.com/hackforla/311-data/issues/1891
  - [ ] https://github.com/hackforla/311-data/issues/1865
  - [ ] Blank Map Feature: No data shown on map when first loaded (?optional)
    - [ insert existing ticket ]
- [ ] Branching Strategy: Local Dev Branch > Staging > Production
  - [ ] https://github.com/hackforla/311-data/issues/1867
  - [ ] https://github.com/hackforla/311-data/issues/1866
- [ ] UXR Wiki - [create ticket here]
- [ ] User Analytics
  - [ ] https://github.com/hackforla/311-data/issues/1592

##### Post-Launch:
- [ ] Map Accessibility
  - [ ] https://github.com/hackforla/311-data/issues/1868

- [ ] Other
  - [ ] https://github.com/hackforla/311-data/issues/1869

  - [ ] User Flow definition
    - [ ] __follow up conversation
  - [ ] Unit Testing, UI Testing
    - [ ] __follow up conversation
  - [ ] QA Testing Process
    - [ ] __follow up conversation
  - [ ] Performance Benchmarking
- [ ] Process Updates:
  - [ ] Updating Milestones
  - [ ] Wiki Updates for v3 app, what is v4 app.
- [ ] Product Testing:
  - [ ] A/B Testing, defining what the use cases are.

**Comment by traycn** [comment]
Updated Pre-Launch issue, adding: https://github.com/hackforla/311-data/issues/1892

**Comment by traycn** [comment]
Added post-launch tickets being discussed and nested a post-launch dev ticket under the 2 MVP solutions. The Blank Map ticket is dependent on the MVP solution fulfilling the definition of done.

**Comment by ryanfchase** [comment]
Need to add this epic:

- [ ] https://github.com/hackforla/311-data/issues/1738
  - [ ] https://github.com/hackforla/311-data/issues/1745
  - [ ] New Ticket(s): Bonnie asked why are we doing a zip file. We could modify our export flow to signify if they are downloading ALL data, or just the aggregate-by-address-for-selected-nc data
  - [ ] New Ticket: We need to rename the files that are being exported to make it abundantly clear what each file contains, we received feedback from Bonnie that the names of the two files in the zip are unclear.

**Comment by ryanfchase** [comment]
Question: Can we adjust the format of this ticket to JUST show open tickets?
