### ISSUE TITLE
[Other Department Partnerships] - Add Additional Map Boundary Areas

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#270]
### Dependency
Waiting for Data Science to complete the following issue https://github.com/hackforla/data-science/issues/118

### Overview
We are exploring partnerships with parts of the city in addition to Neighborhood empowerment. As a part of this, we would like to see how easy it would be to have overlay or area selections of the areas below.  If they aren't hard to get, then let's mock them up so we can have further conversations with these parts of the city.

### Action Items
- [ ] Business Improvement Districts
- [ ] Supervisory Districts

Issues on this topic
- https://github.com/hackforla/311-data/issues/941
- https://github.com/hackforla/311-data/issues/849

**Comment by itsjoycelee** [comment]
Map adjustments:
- [ ]  Boundaries for map images 

- [ ]  Take out pictures for reported instances

**Comment by itsjoycelee** [comment]
Updated prototype [here](https://www.figma.com/proto/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=1917%3A0&scaling=scale-down).

**Comment by itsjoycelee** [comment]
@yuenyilam will have the boundaries completed by this coming Tuesday - 3/3/20
