### ISSUE TITLE
Go through old notes and put a milestone for future features

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#315]
### Overview
We need to start to track backlog as we get suggestions from Various members or our community.  The purpose of this ticket is to both review previous meeting notes for features that are not a part of MVP alpha as well as setup the system to track more features that come in from the upcoming meeting.s

### Action Items

- [ ] Explore Github to determine appropriate tracking for product feature backlog
- [ ] Implement Github Changes
- [ ] Create Feature backlog based on notes and comments from the community thus far.

### Due
This needs to be done prior to UX interviews so we have a place to keep these features better than our icebox with no milestone.

**Comment by johnr54321** [comment]
We are using the Go Live milestone and the Data team has their own board now to track data projects and requests.
