### ISSUE TITLE
backend performance

### ISSUE THREAD

**Issue by jmensch1** [hackforla/311-data#527]
### Description

This is a global ticket for improving the performance of the backend, which will be an ongoing project. It's intended to include tickets that relate to reducing the response times for our endpoints.

### Related tickets

- [x] Establish performance benchmarks for api calls (#529 and #538)
- [x] Indexing of filtered columns (#500). 
- [ ] Improving performance of IN queries (#499) 
- [x] Calculate timetoclose during ingest instead of at runtime (#528)
- [x] Performance of /pins (#552)
- [x] Redis caching layer (#543)
- [x] Server-side map clustering (#565)
- [x] Consolidate endpoints (#605)

**Comment by jmensch1** [comment]
hey @sellnat77 @ryanmswan, just fyi I made this global ticket to address api performance issues.

**Comment by jmensch1** [comment]
These are the times I got on the production server right after the indexes were created in 4f1d199ebf20eead6797717f12230f15a6843079

```
[
  {
    "path": "/pins",
    "executionTimes": {
      "small": 0.0774,
      "medium": 1.2497,
      "large": 21.2495
    }
  },
  {
    "path": "/timetoclose",
    "executionTimes": {
      "small": 0.2011,
      "medium": 1.4268,
      "large": 17.6084
    }
  },
  {
    "path": "/requestfrequency",
    "executionTimes": {
      "small": 0.4329,
      "medium": 1.6353,
      "large": 11.4641
    }
  },
  {
    "path": "/requestcounts",
    "executionTimes": {
      "small": 0.2768,
      "medium": 1.1132,
      "large": 10.3831
    }
  }
]
```
Pretty bad for large requests.

**Comment by jmensch1** [comment]
Postgres is using a bitmap heap scan for filtering the `nc` column when the list is 10 NCs or less, but a sequential scan when the number of NCs greater than 10.

```
EXPLAIN
SELECT requesttype, srnumber, latitude, longitude
FROM ingest_staging_table
WHERE nc IN (2, 4, 5, 6, 7, 8, 9, 10, 11, 13)

Bitmap Heap Scan on ingest_staging_table  (cost=5174.76..258274.28 rows=183033 width=45)
"  Recheck Cond: (nc = ANY ('{2,4,5,6,7,8,9,10,11,13}'::integer[]))"
  ->  Bitmap Index Scan on nc_index  (cost=0.00..5129.00 rows=183033 width=0)
"        Index Cond: (nc = ANY ('{2,4,5,6,7,8,9,10,11,13}'::integer[]))"
```

```
EXPLAIN
SELECT requesttype, srnumber, latitude, longitude
FROM ingest_staging_table
WHERE nc IN (2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14)

Seq Scan on ingest_staging_table  (cost=0.00..265068.87 rows=198262 width=45)
"  Filter: (nc = ANY ('{2,4,5,6,7,8,9,10,11,13,14}'::integer[]))"
```

**Comment by jmensch1** [comment]
4 ways to filter by the `nc` column.

```
# 1
SELECT requesttype, srnumber, latitude, longitude
FROM ingest_staging_table
WHERE nc IN (2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 50, 52, 53, 54, 55, 58, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 84, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102, 104, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128)

# 2
SELECT requesttype, srnumber, latitude, longitude
FROM ingest_staging_table
WHERE nc IN (
  VALUES (2),(4),(5),(6),(7),(8),(9),(10),(11),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(32),(33),(34),(36),(37),(38),(39),(40),(41),(42),(43),(44),(46),(47),(48),(50),(52),(53),(54),(55),(58),(60),(61),(62),(63),(64),(65),(66),(67),(68),(70),(71),(73),(74),(75),(76),(77),(78),(79),(80),(81),(84),(86),(87),(88),(90),(91),(92),(93),(94),(95),(96),(97),(99),(100),(101),(102),(104),(109),(110),(111),(112),(113),(114),(115),(117),(118),(119),(120),(121),(122),(123),(124),(125),(126),(127),(128)
)

# 3
SELECT requesttype, srnumber, latitude, longitude
FROM ingest_staging_table
INNER JOIN (
  VALUES (2),(4),(5),(6),(7),(8),(9),(10),(11),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(32),(33),(34),(36),(37),(38),(39),(40),(41),(42),(43),(44),(46),(47),(48),(50),(52),(53),(54),(55),(58),(60),(61),(62),(63),(64),(65),(66),(67),(68),(70),(71),(73),(74),(75),(76),(77),(78),(79),(80),(81),(84),(86),(87),(88),(90),(91),(92),(93),(94),(95),(96),(97),(99),(100),(101),(102),(104),(109),(110),(111),(112),(113),(114),(115),(117),(118),(119),(120),(121),(122),(123),(124),(125),(126),(127),(128)
) vals(v)
ON (nc = v)

# 4
SELECT requesttype, srnumber, latitude, longitude FROM ingest_staging_table i 
WHERE EXISTS (
	SELECT 1 FROM 
		(VALUES (2),(4),(5),(6),(7),(8),(9),(10),(11),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(32),(33),(34),(36),(37),(38),(39),(40),(41),(42),(43),(44),(46),(47),(48),(50),(52),(53),(54),(55),(58),(60),(61),(62),(63),(64),(65),(66),(67),(68),(70),(71),(73),(74),(75),(76),(77),(78),(79),(80),(81),(84),(86),(87),(88),(90),(91),(92),(93),(94),(95),(96),(97),(99),(100),(101),(102),(104),(109),(110),(111),(112),(113),(114),(115),(117),(118),(119),(120),(121),(122),(123),(124),(125),(126),(127),(128)
		) vals(column1)
	WHERE i.nc = column1
)
```

**Comment by jmensch1** [comment]
postgres runs some queries in parallel: https://www.percona.com/blog/2019/07/30/parallelism-in-postgresql/
