### ISSUE TITLE
Write Article for EmpowerLA Newsletter

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#598]
## Background
EmpowerLA has a monthly newsletter.  We'll need some press to announce our beta release.

## Tasks:

- [ ] Find out when newsletter goes out
- [ ] Incorporate into larger beta release plan
- [ ] Draft Newsletter Article
- [ ] Submit it

## Resources:
