### ISSUE TITLE
EPIC: Analysis Tool Redesign

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#782]
# Description
We need to better understand how we can break our features into beginner / advanced features, make the site more responsive, less confusing, and easier to use.
- Segmentation of Users and features for them
- Increased Responsiveness (27k max)
- Combine Tools

## Action Items
- [ ] Get a list of all features and divide them up into beginner / advanced
- [ ] Design the initial user experience for the beginner user
- [ ] Think about how to add in the advanced features
- [ ] Design a mock-up / prototype in order to use for screening
- [ ] Screen designs and get input
- [ ] Usability testing

## Resources
https://www.figma.com/file/9jUMKrCxEdZnThvS3pXD3d/Mapbox-ideas?node-id=0%3A1
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A2

**Comment by tan-nate** [comment]
hey guys, I did a bit of work on this with the branch [compartmentalized-visualization](https://github.com/hackforla/311-data/tree/compartmentalized-visualization)

**Comment by jmensch1** [comment]
nice Nate!

here's a link to Nate's work: https://311-data-gcu3xwi6k.vercel.app

**Comment by tan-nate** [comment]
hey guys, I added some rough features to [compartmentalized-visualization](https://github.com/hackforla/311-data/tree/compartmentalized-visualization) to allow toggling between open/closed requests and scrolling through the weeks, although the actual data isn't truly closed requests, it's just the data that's currently on the site

**Comment by jmensch1** [comment]
nice! i’ll push it to vercel this afternoon

**Comment by jmensch1** [comment]
here's the link: https://311-data-2aovzttt2.vercel.app Looking good!

**Comment by tan-nate** [comment]
Thank you Jake!!

**Comment by adamkendis** [comment]
@danarchen @jmensch1 @tan-nate 
It's looking very likely we'll have the required v1 features complete within the next two weeks or so. When these are complete, it would be great if we could have another all-devs + UI/UX meeting to go over the latest work on Nate/Jake's mapbox branch. Objectives for this meeting would be:

1. Identify concrete features for v2. 
2. Get features to UI/UX for opinion and any necessary design.
3. Discuss workflow for v2 development. We probably don't want to merge incremental v2 features into `dev`. 
4. Break this all up into manageable pieces and get tickets on the board.

Hopefully we can eliminate most of the confusion around the v2 redesign and establish an organized development path.

**Comment by jmensch1** [comment]
Two weeks? That’s great. Like the plan
