### ISSUE TITLE
[CMPT] Implement integration libraries like web analytics/tracking

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#967]
# Description

- Should be the equivalent of whatever is in current v1

## Action Items / Open Questions

- [x] Is this the same as v1?
- [x] Are there any new ones?
- [x] Can we simplify it / remove items?

**Comment by mattyweb** [comment]
Assumption is no changes we keep:
- mixpanel
- hotjar
- google analytics

Ready to estimate!

**Comment by EchoProject** [comment]
Discuss with @adamkendis and @pras4u which web analytic libraries we're using.
